<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Build valuation, income, depreciation, and linked statements when future cash flows are publicly known.">

<title>2&nbsp; Value and Income Under Certainty – ACCTG 211H Companion</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../arc1-information/03-uncertainty.html" rel="next">
<link href="../arc1-information/01-information.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../accessibility/course.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../arc1-information/01-information.html">Arc I — Information, Value, and Reporting</a></li><li class="breadcrumb-item"><a href="../arc1-information/02-certainty.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Value and Income Under Certainty</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">ACCTG 211H Companion</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/sbb151/acctg211h-companion" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface: Reading, Practice, and Evidence</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Arc I — Information, Value, and Reporting</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc1-information/01-information.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Why Accounting? Information and Cooperation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc1-information/02-certainty.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Value and Income Under Certainty</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc1-information/03-uncertainty.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Value and Income Under Uncertainty</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc1-information/04-information-incentives.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Information, Credibility, and Incentives</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc1-information/05-framework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">From Economic Questions to Accounting Reports</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Arc II — Markets and Measurement</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc2-markets/06-efficient-markets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Efficient Markets and the Information Content of Earnings</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc2-markets/07-accruals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Cash Flows, Accruals, and Earnings Quality</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc2-markets/08-long-term-assets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Long-Term Assets and Measurement Choice</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc2-markets/09-liabilities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Liabilities, Debt Covenants, and Conservatism</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc2-markets/10-equity-compensation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Equity, Compensation, and Reporting Incentives</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Arc III — Contracting and Internal Information</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc3-internal/11-decentralization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Decentralization and Cost Behavior</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc3-internal/12-performance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Performance Measurement as Agency</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc3-internal/13-capital-budgeting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Capital Budgeting Under Asymmetric Information</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Arc IV — Synthesis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc4-synthesis/14-debates.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Synthesis: The Capstone Debates</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/a01-fset.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">A1. The Financial Statement Effects Template</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/a02-python-wrds-colab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">A2. Python + WRDS in Google Colab Quickstart</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/a03-debits-credits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">A3. Debits and Credits</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/a04-tesla-rivian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Tesla and Rivian: Company Connections</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#remove-one-difficulty-before-adding-another" id="toc-remove-one-difficulty-before-adding-another" class="nav-link active" data-scroll-target="#remove-one-difficulty-before-adding-another"><span class="header-section-number">2.1</span> Remove one difficulty before adding another</a></li>
  <li><a href="#a-payment-in-the-future" id="toc-a-payment-in-the-future" class="nav-link" data-scroll-target="#a-payment-in-the-future"><span class="header-section-number">2.2</span> A payment in the future</a></li>
  <li><a href="#the-campus-curb-model-one-operating-asset" id="toc-the-campus-curb-model-one-operating-asset" class="nav-link" data-scroll-target="#the-campus-curb-model-one-operating-asset"><span class="header-section-number">2.3</span> The Campus Curb model: one operating asset</a></li>
  <li><a href="#the-first-year-cash-income-and-capital-recovery" id="toc-the-first-year-cash-income-and-capital-recovery" class="nav-link" data-scroll-target="#the-first-year-cash-income-and-capital-recovery"><span class="header-section-number">2.4</span> The first year: cash, income, and capital recovery</a></li>
  <li><a href="#four-statements-that-tell-one-story" id="toc-four-statements-that-tell-one-story" class="nav-link" data-scroll-target="#four-statements-that-tell-one-story"><span class="header-section-number">2.5</span> Four statements that tell one story</a></li>
  <li><a href="#complete-the-enterprises-life" id="toc-complete-the-enterprises-life" class="nav-link" data-scroll-target="#complete-the-enterprises-life"><span class="header-section-number">2.6</span> Complete the enterprise’s life</a></li>
  <li><a href="#change-the-convention-not-the-business" id="toc-change-the-convention-not-the-business" class="nav-link" data-scroll-target="#change-the-convention-not-the-business"><span class="header-section-number">2.7</span> Change the convention, not the business</a></li>
  <li><a href="#check-your-understanding" id="toc-check-your-understanding" class="nav-link" data-scroll-target="#check-your-understanding"><span class="header-section-number">2.8</span> Check your understanding</a></li>
  <li><a href="#sec-drill-wk02" id="toc-sec-drill-wk02" class="nav-link" data-scroll-target="#sec-drill-wk02"><span class="header-section-number">2.9</span> Week 2 drills: certainty and linked statements</a></li>
  <li><a href="#optional-extension-residual-income" id="toc-optional-extension-residual-income" class="nav-link" data-scroll-target="#optional-extension-residual-income"><span class="header-section-number">2.10</span> Optional extension: residual income</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/sbb151/acctg211h-companion/edit/main/arc1-information/02-certainty.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/sbb151/acctg211h-companion/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../arc1-information/01-information.html">Arc I — Information, Value, and Reporting</a></li><li class="breadcrumb-item"><a href="../arc1-information/02-certainty.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Value and Income Under Certainty</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-certainty" class="quarto-section-identifier"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Value and Income Under Certainty</span></span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note callout-titled" title="Your route through this chapter">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Your route through this chapter
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Week 2 · Required:</strong> the main text and Week 2 drills. Read through <em>A payment in the future</em> and answer reading questions 1–2 before the first meeting; finish the main text and questions 3–5 before the second. Allow 45–60 minutes to read and work examples, then 20 minutes for drills. You need percentages, multiplication, and division; a basic calculator is sufficient.</p>
<p>You should be able to calculate present value, prepare linked statements, separate income from distributions, and compare economic depreciation with cost allocation. The residual-income extension is optional and is not on Quiz 1.</p>
</div>
</div>
<!-- company-context-start -->
<div class="callout callout-style-default callout-tip callout-titled" title="Tesla and Rivian connection">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tesla and Rivian connection
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use <a href="../appendices/a04-tesla-rivian.html#company-c02">the Chapter 2 company prompt</a> when directed in class. Reported facts and constructed assumptions are labeled separately; this connection adds no separate submission.</p>
</div>
</div>
<!-- company-context-end -->
<section id="remove-one-difficulty-before-adding-another" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="remove-one-difficulty-before-adding-another"><span class="header-section-number">2.1</span> Remove one difficulty before adding another</h2>
<p>What would valuation and accounting look like if everyone knew future cash flows and the interest rate? For this chapter, assume there are no taxes or transaction costs and investors can borrow or lend at the same rate. Our small enterprise is financed entirely by owners. These are <strong>model assumptions</strong>, not descriptions of real businesses or requirements of GAAP.</p>
<p>A number can change because time passes, even when nobody learns anything. Income can be positive without being surprising. Cash can be received without all of it being income. Scott develops this ideal-conditions approach <span class="citation" data-cites="scott2020">(<a href="../references.html#ref-scott2020" role="doc-biblioref">Scott and O’Brien 2020, chap. 2</a>)</span>; the numerical cases here are teaching examples.</p>
</section>
<section id="a-payment-in-the-future" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="a-payment-in-the-future"><span class="header-section-number">2.2</span> A payment in the future</h2>
<p><strong>Calculator warm-up.</strong> A 10% annual return turns 100 into 100 × 1.10 = 110 after one year and 110 × 1.10 = 121 after two. To work backward from 121, divide by 1.10 twice. Writing <span class="math inline">\((1.10)^2\)</span> means <span class="math inline">\(1.10\times1.10\)</span>, not <span class="math inline">\(1.10\times2\)</span>. Always count the years between the valuation date and the payment date.</p>
<p>Suppose an investment pays $1,000 exactly two years from now. The annual interest rate is 5%. Investing $100 today gives you $105 after one year and $110.25 after two. Interest in the second year is earned on the accumulated amount.</p>
<p>Work backward to find the amount today that grows to $1,000:</p>
<p><span class="math display">\[
PV_0=\frac{1{,}000}{(1.05)^2}=907.03.
\]</span></p>
<p><strong>Present value</strong> is the value at a specified date of a future cash flow, calculated using a discount rate. The subscript 0 identifies today. One year from now the claim is worth</p>
<p><span class="math display">\[
PV_1=\frac{1{,}000}{1.05}=952.38.
\]</span></p>
<div class="a11y-table-region" role="region" tabindex="0" aria-label="Scrollable data table">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Date</th>
<th style="text-align: right;">0: acquisition</th>
<th style="text-align: right;">1: one year later</th>
<th style="text-align: right;">2: payment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Value of remaining claim</td>
<td style="text-align: right;">$907.03</td>
<td style="text-align: right;">$952.38</td>
<td style="text-align: right;">$0 after collection</td>
</tr>
<tr class="even">
<td>Cash received</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">$0</td>
<td style="text-align: right;">$1,000</td>
</tr>
</tbody>
</table>
</div>
<p>The claim gains $45.35 in Year 1 without a cash receipt. That is <strong>accretion of the discount</strong>: the payment is one year closer. It equals 5% of opening value, subject to rounding. At maturity, the $1,000 receipt includes recovery of the investment, not just the final year’s income.</p>
<p>Why is present value the price in this model? If an identical certain payment could be obtained more cheaply by lending, buyers would choose lending. If the claim offered a better return than the borrowing cost, investors could borrow to acquire it. Under our trading assumptions, those opportunities prevent different prices for identical payments. This is a no-arbitrage argument; it depends on the relevant trades being possible.</p>
</section>
<section id="the-campus-curb-model-one-operating-asset" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="the-campus-curb-model-one-operating-asset"><span class="header-section-number">2.3</span> The Campus Curb model: one operating asset</h2>
<p>A delivery business uses up productive resources. We create a simplified <strong>Campus Curb model enterprise</strong>, separate from the fuller operating-company case in <a href="05-framework.html" class="quarto-xref"><span>Chapter 5</span></a>.</p>
<p>It owns one delivery asset. Net operating cash receipts, after cash operating costs, will be $660 at the end of each of two years. The asset has no resale value after Year 2. The annual interest rate is 10%. All facts are publicly known. The enterprise buys the asset at its present value and immediately distributes each year’s $660 to owners. There are no further contributions, borrowing, or other activities.</p>
<p><span id="eq-certain-value"><span class="math display">\[
V_0=\frac{660}{1.10}+\frac{660}{(1.10)^2}
=600+545.45=1{,}145.45.
\tag{2.1}\]</span></span></p>
<p>Owners contribute $1,145.45 cash; the enterprise exchanges it for the asset. Immediately afterward:</p>
<div class="a11y-table-region" role="region" tabindex="0" aria-label="Scrollable data table">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Opening balance sheet</th>
<th style="text-align: right;">Assets</th>
<th style="text-align: right;">Liabilities and equity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Delivery asset</td>
<td style="text-align: right;">$1,145.45</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td>Liabilities</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">$0.00</td>
</tr>
<tr class="odd">
<td>Contributed equity</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">$1,145.45</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td style="text-align: right;"><strong>$1,145.45</strong></td>
<td style="text-align: right;"><strong>$1,145.45</strong></td>
</tr>
</tbody>
</table>
</div>
<p>The contribution is financing, not income. Purchasing the asset exchanges one resource for another. It does not create an immediate gain or loss in this benchmark.</p>
</section>
<section id="the-first-year-cash-income-and-capital-recovery" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="the-first-year-cash-income-and-capital-recovery"><span class="header-section-number">2.4</span> The first year: cash, income, and capital recovery</h2>
<p>At the end of Year 1, only the second $660 receipt remains. Its present value is $600. The delivery asset’s value falls from $1,145.45 to $600 as the first year’s services are used.</p>
<p><strong>Economic depreciation</strong> is this decline in the productive asset’s value in our certainty example:</p>
<p><span class="math display">\[
1{,}145.45-600=545.45.
\]</span></p>
<p>Economic income is net cash generated less the reduction in asset value:</p>
<p><span class="math display">\[
I_1=660-545.45=114.55.
\]</span></p>
<p>Equivalently, the owner’s economic income is the distribution plus the change in the remaining investment’s value:</p>
<p><span id="eq-economic-income"><span class="math display">\[
I_1=D_1+V_1-V_0=660+600-1{,}145.45=114.55.
\tag{2.2}\]</span></span></p>
<p>Here <span class="math inline">\(D_t\)</span> is the distribution and <span class="math inline">\(V_t\)</span> is enterprise value <strong>after</strong> that distribution. There are no new contributions in this formula. A contribution must be excluded from income, just as we excluded the initial contribution.</p>
<p><strong>Keep dates and periods separate.</strong> Asset value and equity describe what remains <strong>at a date</strong>; receipts, distributions, and income describe what happens <strong>during a period</strong>. In this all-equity model, enterprise value equals the value of all remaining assets, including any retained cash. It equals the delivery asset alone only when there is no other asset. We are using present values here; a later accounting carrying amount need not equal economic value.</p>
<p>Of the $660 received, $114.55 is a return on the investment and the remainder is capital recovery. Income is also 10% of opening value: $1,145.45 × 10% = $114.55.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="A distribution is not an expense">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
A distribution is not an expense
</div>
</div>
<div class="callout-body-container callout-body">
<p>Generating income and distributing cash are different events. If the enterprise instead kept the $660 at year-end, it would have $660 cash plus the $600 asset. Total value would be $1,260, with the same $114.55 income. A distribution reduces cash and equity; it does not reduce income.</p>
</div>
</div>
<p><strong>Try a partial distribution.</strong> Suppose Campus Curb distributes only $400 of Year 1’s receipt and keeps the rest as cash at the reporting instant. Find closing cash, total assets, equity, and income before opening the answer. Everything else is unchanged.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Check the partial-distribution case">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check the partial-distribution case
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Cash is $260. The delivery asset is still worth $600, so total assets and equity are $860. Income is $400 + $860 − $1,145.45 = $114.55. Counting the full receipt as a distribution would count the retained $260 twice. Changing the payout alone has not changed this year’s income; future returns on retained cash are outside this reporting instant.</p>
</div>
</div>
</div>
</section>
<section id="four-statements-that-tell-one-story" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="four-statements-that-tell-one-story"><span class="header-section-number">2.5</span> Four statements that tell one story</h2>
<p>These statements apply the present-value model. They are not a complete GAAP presentation.</p>
<div class="a11y-table-region" role="region" tabindex="0" aria-label="Scrollable data table">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Year 1 income statement</th>
<th style="text-align: right;">Amount</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Net operating receipts before economic depreciation</td>
<td style="text-align: right;">$660.00</td>
</tr>
<tr class="even">
<td>Economic depreciation</td>
<td style="text-align: right;">(545.45)</td>
</tr>
<tr class="odd">
<td><strong>Economic income</strong></td>
<td style="text-align: right;"><strong>$114.55</strong></td>
</tr>
</tbody>
</table>
</div>
<p>Net operating receipts keep this example small. A fuller income statement distinguishes revenues from individual operating expenses.</p>
<div class="a11y-table-region" role="region" tabindex="0" aria-label="Scrollable data table">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Year 1 changes in equity</th>
<th style="text-align: right;">Amount</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Equity immediately after acquisition</td>
<td style="text-align: right;">$1,145.45</td>
</tr>
<tr class="even">
<td>Add economic income</td>
<td style="text-align: right;">114.55</td>
</tr>
<tr class="odd">
<td>Less distribution</td>
<td style="text-align: right;">(660.00)</td>
</tr>
<tr class="even">
<td><strong>Closing equity</strong></td>
<td style="text-align: right;"><strong>$600.00</strong></td>
</tr>
</tbody>
</table>
</div>
<div class="a11y-table-region" role="region" tabindex="0" aria-label="Scrollable data table">
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 36%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Closing balance sheet, after distribution</th>
<th style="text-align: right;">Assets</th>
<th style="text-align: right;">Liabilities and equity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cash</td>
<td style="text-align: right;">$0.00</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="even">
<td>Delivery asset</td>
<td style="text-align: right;">600.00</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="odd">
<td>Liabilities</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">$0.00</td>
</tr>
<tr class="even">
<td>Equity</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">600.00</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: right;"><strong>$600.00</strong></td>
<td style="text-align: right;"><strong>$600.00</strong></td>
</tr>
</tbody>
</table>
</div>
<div class="a11y-table-region" role="region" tabindex="0" aria-label="Scrollable data table">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Year 1 cash flows, measured after the initial acquisition</th>
<th style="text-align: right;">Amount</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Net cash from operations</td>
<td style="text-align: right;">$660.00</td>
</tr>
<tr class="even">
<td>New investing cash flows</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="odd">
<td>Distribution to owners</td>
<td style="text-align: right;">(660.00)</td>
</tr>
<tr class="even">
<td><strong>Change in cash</strong></td>
<td style="text-align: right;"><strong>$0.00</strong></td>
</tr>
</tbody>
</table>
</div>
<p>The statements reconcile. Cash generated differs from income; income and distributions change equity; closing equity equals net assets. A zero change in cash does not imply zero income.</p>
</section>
<section id="complete-the-enterprises-life" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="complete-the-enterprises-life"><span class="header-section-number">2.6</span> Complete the enterprise’s life</h2>
<p>In Year 2 the asset produces its final $660 and has no remaining value. Economic depreciation is $600, income is $60, and the distribution is $660.</p>
<div class="a11y-table-region" role="region" tabindex="0" aria-label="Scrollable data table">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Item</th>
<th style="text-align: right;">Year 1</th>
<th style="text-align: right;">Year 2</th>
<th style="text-align: right;">Lifetime total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cash generated</td>
<td style="text-align: right;">$660.00</td>
<td style="text-align: right;">$660.00</td>
<td style="text-align: right;">$1,320.00</td>
</tr>
<tr class="even">
<td>Economic depreciation</td>
<td style="text-align: right;">545.45</td>
<td style="text-align: right;">600.00</td>
<td style="text-align: right;">1,145.45</td>
</tr>
<tr class="odd">
<td>Economic income</td>
<td style="text-align: right;">114.55</td>
<td style="text-align: right;">60.00</td>
<td style="text-align: right;">174.55</td>
</tr>
<tr class="even">
<td>Closing asset after distribution</td>
<td style="text-align: right;">600.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">—</td>
</tr>
</tbody>
</table>
</div>
<p>Lifetime income is receipts less the initial investment: $1,320 − $1,145.45 = $174.55. Both annual incomes were knowable at acquisition. The income statements record performance but add no <strong>new valuation information</strong> to what everyone already knew.</p>
<p>Records still document ownership claims and scheduled payments. It is the surprise and forecasting roles of income that disappear under these strong assumptions.</p>
</section>
<section id="change-the-convention-not-the-business" class="level2" data-number="2.7">
<h2 data-number="2.7" class="anchored" data-anchor-id="change-the-convention-not-the-business"><span class="header-section-number">2.7</span> Change the convention, not the business</h2>
<p>Keep every cash flow unchanged, but allocate acquisition cost equally over two years. <strong>Straight-line depreciation</strong>, with zero residual value, is</p>
<p><span class="math display">\[
\frac{1{,}145.45}{2}\approx572.73\text{ per year}.
\]</span></p>
<p>Accounting income becomes approximately $660 − $572.73 = $87.27 each year. Use unrounded calculations and adjust the final cent when presenting a complete rounded schedule.</p>
<div class="a11y-table-region" role="region" tabindex="0" aria-label="Scrollable data table">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Convention</th>
<th style="text-align: right;">Year 1 income</th>
<th style="text-align: right;">Year 1 closing asset</th>
<th style="text-align: right;">Year 2 income</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Present-value model</td>
<td style="text-align: right;">$114.55</td>
<td style="text-align: right;">$600.00</td>
<td style="text-align: right;">$60.00</td>
</tr>
<tr class="even">
<td>Equal allocation of acquisition cost</td>
<td style="text-align: right;">About $87.27</td>
<td style="text-align: right;">About $572.73</td>
<td style="text-align: right;">About $87.27</td>
</tr>
</tbody>
</table>
</div>
<p>The convention changes reported income timing and carrying amounts. It does not change customer payments, productivity, or economic value in this example. Both conventions recognize the same lifetime cost.</p>
<p>Later we ask whether a measure helps users predict cash flows, evaluate management, compare firms, or verify reports. Selecting the measure with the largest current profit is not a sufficient answer.</p>
</section>
<section id="check-your-understanding" class="level2" data-number="2.8">
<h2 data-number="2.8" class="anchored" data-anchor-id="check-your-understanding"><span class="header-section-number">2.8</span> Check your understanding</h2>
<p>Explain why income can be positive when the productive asset falls in value; why a distribution can exceed income; why predictable income is not news; and why depreciation conventions can change income without changing cash flows.</p>
<p><a href="../drills/pdf/wk02-drills.pdf">Printable drill sheet</a> · <a href="../drills/pdf/wk02-drills-key.pdf">Self-check key</a></p>
</section>
<section id="sec-drill-wk02" class="level2" data-number="2.9">
<h2 data-number="2.9" class="anchored" data-anchor-id="sec-drill-wk02"><span class="header-section-number">2.9</span> Week 2 drills: certainty and linked statements</h2>
<p>Work individually with a calculator, check the key, and correct errors. Submit before Day 4; these drills are practice after Day 3’s demonstration. Graded for completion. Do not use generative AI.</p>
<ol type="1">
<li>A claim pays $121 in two years. At 10%, calculate its value today, its value one year later before any payment, and first-year income.</li>
<li>An all-equity model enterprise costs its present value and distributes certain net receipts of $110 at the end of Year 1 and $121 at the end of Year 2. The rate is 10%, terminal value is zero, and there are no other transactions. Calculate opening value, Year 1 closing value after distribution, and each year’s economic income.</li>
<li>In Problem 2, keep the Year 1 receipt as cash at year-end instead of distributing it. Give closing cash, the productive asset’s value, total equity, and Year 1 income. Do not project a second-year return on the retained cash.</li>
<li>Allocate Problem 2’s acquisition cost evenly over its two years instead. Calculate annual depreciation and each year’s accounting income. Does this choice change the given cash flows or initial economic value?</li>
<li>A new organization receives $50 from its owners and borrows $30. It has done nothing else. Give cash, liabilities, equity, and income. Explain why an $80 cash inflow is not $80 of revenue.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Drill answers">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Drill answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Present value = 121/1.10² = <strong>$100</strong>. Year 1 value = 121/1.10 = <strong>$110</strong>. Income = <strong>$10</strong>.</li>
<li>Opening value = 110/1.10 + 121/1.10² = <strong>$200</strong>. Closing Year 1 value = <strong>$110</strong>. Year 1 income = 110 + 110 − 200 = <strong>$20</strong>. Year 2 income = 121 − 110 = <strong>$11</strong>. Lifetime income is $31.</li>
<li>Cash <strong>$110</strong>, productive asset <strong>$110</strong>, equity <strong>$220</strong>, income <strong>$20</strong>. No distribution occurred; retaining cash does not erase income.</li>
<li>Annual depreciation <strong>$100</strong>. Income is <strong>$10</strong> and <strong>$21</strong>. Lifetime income remains $31; given cash flows and initial value are unchanged.</li>
<li>Cash <strong>$80</strong>, liabilities <strong>$30</strong>, equity <strong>$50</strong>, income <strong>$0</strong>. Contributions and borrowing are financing transactions.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="optional-extension-residual-income" class="level2" data-number="2.10">
<h2 data-number="2.10" class="anchored" data-anchor-id="optional-extension-residual-income"><span class="header-section-number">2.10</span> Optional extension: residual income</h2>
<p>If owners require return <span class="math inline">\(r\)</span> on beginning book equity <span class="math inline">\(B_{t-1}\)</span>, define <strong>residual income</strong> as accounting income after a charge for capital:</p>
<p><span class="math display">\[
RI_t=NI_t-rB_{t-1}.
\]</span></p>
<p>Under our present-value convention, income equals the required return and residual income is zero. Under equal cost allocation, first-year residual income is approximately −$27.27 and second-year residual income is $30. Their discounted sum is zero. Book equity plus discounted residual income gives the same initial valuation.</p>
<p>More generally, under the appropriate clean-surplus relation between income, equity, and net owner distributions, and a terminal condition, value can be expressed using book equity and discounted expected future residual income. The formula <span class="math inline">\(V=B+RI/r\)</span> is a constant-perpetuity special case, not a general rule for valuing firms.</p>
<p>Next, the final cash receipt becomes uncertain. Income will contain an expected return and unexpected news.</p>


<!-- -->

<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-scott2020" class="csl-entry" role="listitem">
Scott, William R., and Patricia C. O’Brien. 2020. <em>Financial Accounting Theory</em>. 8th ed. North York, Ontario: Pearson Canada.
</div>
</div>
</section>

</main> <!-- /main -->
<footer class="course-accessibility"><p><a href="https://www.psu.edu/accessibilitystatement">Penn State accessibility statement</a> · <a href="mailto:accessibility@psu.edu">Report an accessibility barrier to the Penn State IT Accessibility Team</a>. Include the page address and a description of the issue.</p></footer>
<script>
document.addEventListener('DOMContentLoaded', function () {
  document.querySelectorAll('main table').forEach(function (table) {
    table.querySelectorAll('thead th').forEach(function (th) { th.scope = 'col'; });
    table.querySelectorAll('tbody tr').forEach(function (row) {
      var first = row.firstElementChild;
      if (first && first.tagName === 'TD' && first.textContent.trim()) {
        var th = document.createElement('th');
        th.scope = 'row'; th.innerHTML = first.innerHTML;
        th.style.cssText = first.style.cssText; th.style.fontWeight = 'normal';
        first.replaceWith(th);
      }
    });
    var region = table.closest('.a11y-table-region');
    if (region && region.getAttribute('aria-label') === 'Scrollable data table') {
      var section = table.closest('section');
      var heading = section && section.querySelector('h1,h2,h3,h4,h5,h6');
      if (heading) region.setAttribute('aria-label', heading.textContent.trim() + ' — data table');
    }
  });
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/sbb151\.github\.io\/acctg211h-companion\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../arc1-information/01-information.html" class="pagination-link" aria-label="Why Accounting? Information and Cooperation">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Why Accounting? Information and Cooperation</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../arc1-information/03-uncertainty.html" class="pagination-link" aria-label="Value and Income Under Uncertainty">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Value and Income Under Uncertainty</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Build valuation, income, depreciation, and linked statements when future cash flows are publicly known."</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu"># Value and Income Under Certainty {#sec-certainty}</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="Your route through this chapter"}</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>**Week 2 · Required:** the main text and Week 2 drills. Read through *A payment in the future* and answer reading questions 1–2 before the first meeting; finish the main text and questions 3–5 before the second. Allow 45–60 minutes to read and work examples, then 20 minutes for drills. You need percentages, multiplication, and division; a basic calculator is sufficient.</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>You should be able to calculate present value, prepare linked statements, separate income from distributions, and compare economic depreciation with cost allocation. The residual-income extension is optional and is not on Quiz 1.</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- company-context-start --&gt;</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Tesla and Rivian connection"}</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>Use <span class="co">[</span><span class="ot">the Chapter 2 company prompt</span><span class="co">](../appendices/a04-tesla-rivian.qmd#company-c02)</span> when directed in class. Reported facts and constructed assumptions are labeled separately; this connection adds no separate submission.</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- company-context-end --&gt;</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="fu">## Remove one difficulty before adding another</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>What would valuation and accounting look like if everyone knew future cash flows and the interest rate? For this chapter, assume there are no taxes or transaction costs and investors can borrow or lend at the same rate. Our small enterprise is financed entirely by owners. These are **model assumptions**, not descriptions of real businesses or requirements of GAAP.</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>A number can change because time passes, even when nobody learns anything. Income can be positive without being surprising. Cash can be received without all of it being income. Scott develops this ideal-conditions approach <span class="co">[</span><span class="ot">@scott2020, Chapter 2</span><span class="co">]</span>; the numerical cases here are teaching examples.</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="fu">## A payment in the future</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>**Calculator warm-up.** A 10% annual return turns 100 into 100 × 1.10 = 110 after one year and 110 × 1.10 = 121 after two. To work backward from 121, divide by 1.10 twice. Writing $(1.10)^2$ means $1.10\times1.10$, not $1.10\times2$. Always count the years between the valuation date and the payment date.</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>Suppose an investment pays \$1,000 exactly two years from now. The annual interest rate is 5%. Investing \$100 today gives you \$105 after one year and \$110.25 after two. Interest in the second year is earned on the accumulated amount.</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>Work backward to find the amount today that grows to \$1,000:</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>PV_0=\frac{1{,}000}{(1.05)^2}=907.03.</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>**Present value** is the value at a specified date of a future cash flow, calculated using a discount rate. The subscript 0 identifies today. One year from now the claim is worth</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>PV_1=\frac{1{,}000}{1.05}=952.38.</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>| Date | 0: acquisition | 1: one year later | 2: payment |</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>|---|---:|---:|---:|</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>| Value of remaining claim | \$907.03 | \$952.38 | \$0 after collection |</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>| Cash received | — | \$0 | \$1,000 |</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>The claim gains \$45.35 in Year 1 without a cash receipt. That is **accretion of the discount**: the payment is one year closer. It equals 5% of opening value, subject to rounding. At maturity, the \$1,000 receipt includes recovery of the investment, not just the final year's income.</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>Why is present value the price in this model? If an identical certain payment could be obtained more cheaply by lending, buyers would choose lending. If the claim offered a better return than the borrowing cost, investors could borrow to acquire it. Under our trading assumptions, those opportunities prevent different prices for identical payments. This is a no-arbitrage argument; it depends on the relevant trades being possible.</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Campus Curb model: one operating asset</span></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>A delivery business uses up productive resources. We create a simplified **Campus Curb model enterprise**, separate from the fuller operating-company case in @sec-standards.</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>It owns one delivery asset. Net operating cash receipts, after cash operating costs, will be \$660 at the end of each of two years. The asset has no resale value after Year 2. The annual interest rate is 10%. All facts are publicly known. The enterprise buys the asset at its present value and immediately distributes each year's \$660 to owners. There are no further contributions, borrowing, or other activities.</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>V_0=\frac{660}{1.10}+\frac{660}{(1.10)^2}</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>=600+545.45=1{,}145.45.</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>$$ {#eq-certain-value}</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>Owners contribute \$1,145.45 cash; the enterprise exchanges it for the asset. Immediately afterward:</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>| Opening balance sheet | Assets | Liabilities and equity |</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>|---|---:|---:|</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>| Delivery asset | \$1,145.45 | — |</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>| Liabilities | — | \$0.00 |</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>| Contributed equity | — | \$1,145.45 |</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>| **Total** | **\$1,145.45** | **\$1,145.45** |</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>The contribution is financing, not income. Purchasing the asset exchanges one resource for another. It does not create an immediate gain or loss in this benchmark.</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a><span class="fu">## The first year: cash, income, and capital recovery</span></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>At the end of Year 1, only the second \$660 receipt remains. Its present value is \$600. The delivery asset's value falls from \$1,145.45 to \$600 as the first year's services are used.</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>**Economic depreciation** is this decline in the productive asset's value in our certainty example:</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>1{,}145.45-600=545.45.</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>Economic income is net cash generated less the reduction in asset value:</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>I_1=660-545.45=114.55.</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a>Equivalently, the owner's economic income is the distribution plus the change in the remaining investment's value:</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>I_1=D_1+V_1-V_0=660+600-1{,}145.45=114.55.</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a>$$ {#eq-economic-income}</span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a>Here $D_t$ is the distribution and $V_t$ is enterprise value **after** that distribution. There are no new contributions in this formula. A contribution must be excluded from income, just as we excluded the initial contribution.</span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a>**Keep dates and periods separate.** Asset value and equity describe what remains **at a date**; receipts, distributions, and income describe what happens **during a period**. In this all-equity model, enterprise value equals the value of all remaining assets, including any retained cash. It equals the delivery asset alone only when there is no other asset. We are using present values here; a later accounting carrying amount need not equal economic value.</span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>Of the \$660 received, \$114.55 is a return on the investment and the remainder is capital recovery. Income is also 10% of opening value: \$1,145.45 × 10% = \$114.55.</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a>::: {.callout-warning title="A distribution is not an expense"}</span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a>Generating income and distributing cash are different events. If the enterprise instead kept the \$660 at year-end, it would have \$660 cash plus the \$600 asset. Total value would be \$1,260, with the same \$114.55 income. A distribution reduces cash and equity; it does not reduce income.</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>**Try a partial distribution.** Suppose Campus Curb distributes only \$400 of Year 1's receipt and keeps the rest as cash at the reporting instant. Find closing cash, total assets, equity, and income before opening the answer. Everything else is unchanged.</span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="Check the partial-distribution case" collapse="true"}</span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>Cash is \$260. The delivery asset is still worth \$600, so total assets and equity are \$860. Income is \$400 + \$860 − \$1,145.45 = \$114.55. Counting the full receipt as a distribution would count the retained \$260 twice. Changing the payout alone has not changed this year's income; future returns on retained cash are outside this reporting instant.</span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a><span class="fu">## Four statements that tell one story</span></span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a>These statements apply the present-value model. They are not a complete GAAP presentation.</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>| Year 1 income statement | Amount |</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a>|---|---:|</span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a>| Net operating receipts before economic depreciation | \$660.00 |</span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>| Economic depreciation | (545.45) |</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a>| **Economic income** | **\$114.55** |</span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a>Net operating receipts keep this example small. A fuller income statement distinguishes revenues from individual operating expenses.</span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>| Year 1 changes in equity | Amount |</span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>|---|---:|</span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>| Equity immediately after acquisition | \$1,145.45 |</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>| Add economic income | 114.55 |</span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a>| Less distribution | (660.00) |</span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a>| **Closing equity** | **\$600.00** |</span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a>| Closing balance sheet, after distribution | Assets | Liabilities and equity |</span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a>|---|---:|---:|</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a>| Cash | \$0.00 | — |</span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a>| Delivery asset | 600.00 | — |</span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a>| Liabilities | — | \$0.00 |</span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a>| Equity | — | 600.00 |</span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a>| **Total** | **\$600.00** | **\$600.00** |</span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a>| Year 1 cash flows, measured after the initial acquisition | Amount |</span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>|---|---:|</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a>| Net cash from operations | \$660.00 |</span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>| New investing cash flows | 0.00 |</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>| Distribution to owners | (660.00) |</span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>| **Change in cash** | **\$0.00** |</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a>The statements reconcile. Cash generated differs from income; income and distributions change equity; closing equity equals net assets. A zero change in cash does not imply zero income.</span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a><span class="fu">## Complete the enterprise's life</span></span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a>In Year 2 the asset produces its final \$660 and has no remaining value. Economic depreciation is \$600, income is \$60, and the distribution is \$660.</span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a>| Item | Year 1 | Year 2 | Lifetime total |</span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a>|---|---:|---:|---:|</span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>| Cash generated | \$660.00 | \$660.00 | \$1,320.00 |</span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a>| Economic depreciation | 545.45 | 600.00 | 1,145.45 |</span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a>| Economic income | 114.55 | 60.00 | 174.55 |</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a>| Closing asset after distribution | 600.00 | 0.00 | — |</span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a>Lifetime income is receipts less the initial investment: \$1,320 − \$1,145.45 = \$174.55. Both annual incomes were knowable at acquisition. The income statements record performance but add no **new valuation information** to what everyone already knew.</span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a>Records still document ownership claims and scheduled payments. It is the surprise and forecasting roles of income that disappear under these strong assumptions.</span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a><span class="fu">## Change the convention, not the business</span></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a>Keep every cash flow unchanged, but allocate acquisition cost equally over two years. **Straight-line depreciation**, with zero residual value, is</span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a>\frac{1{,}145.45}{2}\approx572.73\text{ per year}.</span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a>Accounting income becomes approximately \$660 − \$572.73 = \$87.27 each year. Use unrounded calculations and adjust the final cent when presenting a complete rounded schedule.</span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a>| Convention | Year 1 income | Year 1 closing asset | Year 2 income |</span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a>|---|---:|---:|---:|</span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a>| Present-value model | \$114.55 | \$600.00 | \$60.00 |</span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a>| Equal allocation of acquisition cost | About \$87.27 | About \$572.73 | About \$87.27 |</span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a>The convention changes reported income timing and carrying amounts. It does not change customer payments, productivity, or economic value in this example. Both conventions recognize the same lifetime cost.</span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a>Later we ask whether a measure helps users predict cash flows, evaluate management, compare firms, or verify reports. Selecting the measure with the largest current profit is not a sufficient answer.</span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a><span class="fu">## Check your understanding</span></span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a>Explain why income can be positive when the productive asset falls in value; why a distribution can exceed income; why predictable income is not news; and why depreciation conventions can change income without changing cash flows.</span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Printable drill sheet</span><span class="co">](../drills/pdf/wk02-drills.pdf)</span> · <span class="co">[</span><span class="ot">Self-check key</span><span class="co">](../drills/pdf/wk02-drills-key.pdf)</span></span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a>{{&lt; include ../drills/drill-wk02.qmd &gt;}}</span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="Drill answers" collapse="true"}</span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a>{{&lt; include ../drills/key-wk02.qmd &gt;}}</span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a><span class="fu">## Optional extension: residual income</span></span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a>If owners require return $r$ on beginning book equity $B_{t-1}$, define **residual income** as accounting income after a charge for capital:</span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a>RI_t=NI_t-rB_{t-1}.</span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a>Under our present-value convention, income equals the required return and residual income is zero. Under equal cost allocation, first-year residual income is approximately −\$27.27 and second-year residual income is \$30. Their discounted sum is zero. Book equity plus discounted residual income gives the same initial valuation.</span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a>More generally, under the appropriate clean-surplus relation between income, equity, and net owner distributions, and a terminal condition, value can be expressed using book equity and discounted expected future residual income. The formula $V=B+RI/r$ is a constant-perpetuity special case, not a general rule for valuing firms.</span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a>Next, the final cash receipt becomes uncertain. Income will contain an expected return and unexpected news.</span></code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/sbb151/acctg211h-companion/edit/main/arc1-information/02-certainty.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/sbb151/acctg211h-companion/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>