<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Separate expected income from news, expected losses from priced risk, and shared uncertainty from unequal information.">

<title>3&nbsp; Value and Income Under Uncertainty – ACCTG 211H Companion</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../arc1-information/04-information-incentives.html" rel="next">
<link href="../arc1-information/02-certainty.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../accessibility/course.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../arc1-information/01-information.html">Arc I — Information, Value, and Reporting</a></li><li class="breadcrumb-item"><a href="../arc1-information/03-uncertainty.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Value and Income Under Uncertainty</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">ACCTG 211H Companion</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/sbb151/acctg211h-companion" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface: Reading, Practice, and Evidence</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Arc I — Information, Value, and Reporting</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc1-information/01-information.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Why Accounting? Information and Cooperation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc1-information/02-certainty.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Value and Income Under Certainty</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc1-information/03-uncertainty.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Value and Income Under Uncertainty</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc1-information/04-information-incentives.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Information, Credibility, and Incentives</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc1-information/05-framework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">From Economic Questions to Accounting Reports</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Arc II — Markets and Measurement</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc2-markets/06-efficient-markets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Efficient Markets and the Information Content of Earnings</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc2-markets/07-accruals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Cash Flows, Accruals, and Earnings Quality</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc2-markets/08-long-term-assets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Long-Term Assets and Measurement Choice</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc2-markets/09-liabilities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Liabilities, Debt Covenants, and Conservatism</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc2-markets/10-equity-compensation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Equity, Compensation, and Reporting Incentives</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Arc III — Contracting and Internal Information</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc3-internal/11-decentralization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Decentralization and Cost Behavior</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc3-internal/12-performance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Performance Measurement as Agency</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc3-internal/13-capital-budgeting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Capital Budgeting Under Asymmetric Information</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Arc IV — Synthesis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc4-synthesis/14-debates.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Synthesis: The Capstone Debates</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/a01-fset.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">A1. The Financial Statement Effects Template</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/a02-python-wrds-colab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">A2. Python + WRDS in Google Colab Quickstart</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/a03-debits-credits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">A3. Debits and Credits</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/a04-tesla-rivian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Tesla and Rivian: Company Connections</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#an-uncertain-outcome-need-not-be-private-information" id="toc-an-uncertain-outcome-need-not-be-private-information" class="nav-link active" data-scroll-target="#an-uncertain-outcome-need-not-be-private-information"><span class="header-section-number">3.1</span> An uncertain outcome need not be private information</a></li>
  <li><a href="#an-expected-value-is-a-weighted-average" id="toc-an-expected-value-is-a-weighted-average" class="nav-link" data-scroll-target="#an-expected-value-is-a-weighted-average"><span class="header-section-number">3.2</span> An expected value is a weighted average</a></li>
  <li><a href="#the-same-enterprise-with-an-uncertain-final-receipt" id="toc-the-same-enterprise-with-an-uncertain-final-receipt" class="nav-link" data-scroll-target="#the-same-enterprise-with-an-uncertain-final-receipt"><span class="header-section-number">3.3</span> The same enterprise with an uncertain final receipt</a></li>
  <li><a href="#separate-the-passage-of-time-from-news" id="toc-separate-the-passage-of-time-from-news" class="nav-link" data-scroll-target="#separate-the-passage-of-time-from-news"><span class="header-section-number">3.4</span> Separate the passage of time from news</a></li>
  <li><a href="#accounting-for-the-state-revelation" id="toc-accounting-for-the-state-revelation" class="nav-link" data-scroll-target="#accounting-for-the-state-revelation"><span class="header-section-number">3.5</span> Accounting for the state revelation</a></li>
  <li><a href="#expected-loss-is-not-the-same-as-a-price-of-risk" id="toc-expected-loss-is-not-the-same-as-a-price-of-risk" class="nav-link" data-scroll-target="#expected-loss-is-not-the-same-as-a-price-of-risk"><span class="header-section-number">3.6</span> Expected loss is not the same as a price of risk</a></li>
  <li><a href="#a-useful-report-can-deliver-bad-news" id="toc-a-useful-report-can-deliver-bad-news" class="nav-link" data-scroll-target="#a-useful-report-can-deliver-bad-news"><span class="header-section-number">3.7</span> A useful report can deliver bad news</a></li>
  <li><a href="#evidence-habits-prediction-is-not-proof" id="toc-evidence-habits-prediction-is-not-proof" class="nav-link" data-scroll-target="#evidence-habits-prediction-is-not-proof"><span class="header-section-number">3.8</span> Evidence habits: prediction is not proof</a></li>
  <li><a href="#check-your-understanding" id="toc-check-your-understanding" class="nav-link" data-scroll-target="#check-your-understanding"><span class="header-section-number">3.9</span> Check your understanding</a></li>
  <li><a href="#sec-drill-wk03" id="toc-sec-drill-wk03" class="nav-link" data-scroll-target="#sec-drill-wk03"><span class="header-section-number">3.10</span> Week 3 drills: uncertainty and news</a></li>
  <li><a href="#optional-extension-uncertain-probabilities" id="toc-optional-extension-uncertain-probabilities" class="nav-link" data-scroll-target="#optional-extension-uncertain-probabilities"><span class="header-section-number">3.11</span> Optional extension: uncertain probabilities</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/sbb151/acctg211h-companion/edit/main/arc1-information/03-uncertainty.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/sbb151/acctg211h-companion/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../arc1-information/01-information.html">Arc I — Information, Value, and Reporting</a></li><li class="breadcrumb-item"><a href="../arc1-information/03-uncertainty.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Value and Income Under Uncertainty</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-uncertainty" class="quarto-section-identifier"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Value and Income Under Uncertainty</span></span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note callout-titled" title="Your route through this chapter">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Your route through this chapter
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Week 3 · Required:</strong> the main text and Week 3 drills. Read through <em>The same enterprise with an uncertain final receipt</em> and answer reading questions 1–3 before the first meeting; finish the main text and questions 4–5 before the second. Allow 45–60 minutes for text and worked examples, plus 20 minutes for drills. Review <a href="02-certainty.html#eq-economic-income" class="quarto-xref">Equation&nbsp;<span>2.2</span></a> if the distribution/value distinction is unfamiliar.</p>
<p>You should be able to compute expected payoffs, value our simplified uncertain enterprise, reconcile statements after news, and explain why a lower expected payoff is different from a risk premium. No calculus or statistical software is required.</p>
</div>
</div>
<!-- company-context-start -->
<div class="callout callout-style-default callout-tip callout-titled" title="Tesla and Rivian connection">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tesla and Rivian connection
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use <a href="../appendices/a04-tesla-rivian.html#company-c03">the Chapter 3 company prompt</a> when directed in class. Reported facts and constructed assumptions are labeled separately; this connection adds no separate submission.</p>
</div>
</div>
<!-- company-context-end -->
<section id="an-uncertain-outcome-need-not-be-private-information" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="an-uncertain-outcome-need-not-be-private-information"><span class="header-section-number">3.1</span> An uncertain outcome need not be private information</h2>
<p>Campus Curb’s founders and investors might agree on the possible outcomes and their probabilities without knowing which will occur. This is uncertainty with <strong>symmetric information</strong>. It is different from a manager concealing a fact already known to her.</p>
<p>In this chapter, everyone shares the same probability model. Investors are <strong>risk neutral</strong>: for the payoffs considered here they value an uncertain dollar amount at its expected amount before discounting for time. They can borrow and lend at the stated interest rate, and we retain the other simplifying assumptions from <a href="02-certainty.html" class="quarto-xref"><span>Chapter 2</span></a>. These assumptions let us introduce uncertainty without simultaneously introducing a pricing model for risk or a credibility problem.</p>
<p>Risk neutrality is a teaching assumption. It does not mean that real investors are indifferent to all risks or that a risky investment should always be discounted at the risk-free rate.</p>
</section>
<section id="an-expected-value-is-a-weighted-average" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="an-expected-value-is-a-weighted-average"><span class="header-section-number">3.2</span> An expected value is a weighted average</h2>
<p>Suppose a claim pays $880 in a high-demand state and $440 in a low-demand state. Each state has probability 0.5. Its <strong>expected payoff</strong> is</p>
<p><span class="math display">\[
E[X]=0.5(880)+0.5(440)=660.
\]</span></p>
<p>The weights sum to one. They describe our uncertainty, not a promise to receive part of each outcome. The actual receipt will be $880 or $440; it will never be $660 in this example. An expectation can be useful even though it is not a possible realization.</p>
<p>A report that estimates $660 has not necessarily made an error when the outcome is $440. To judge the estimate, ask what information was available when it was made, whether the probability model was appropriate, and whether that model was applied honestly and correctly. A single unfavorable outcome cannot answer all those questions.</p>
</section>
<section id="the-same-enterprise-with-an-uncertain-final-receipt" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="the-same-enterprise-with-an-uncertain-final-receipt"><span class="header-section-number">3.3</span> The same enterprise with an uncertain final receipt</h2>
<p>Return to the Campus Curb model enterprise. Keep Year 1’s net cash receipt of $660 certain. Year 2’s receipt is now $880 or $440, with equal probability. The annual rate remains 10%, the asset has no value after Year 2, all cash receipts are immediately distributed, and there is no debt. At acquisition, everyone knows this distribution.</p>
<p>At the <strong>end of Year 1</strong>, just after the first receipt and distribution, the demand state is publicly revealed. After revelation, the appropriate Year 2 receipt is known with certainty. This timing is essential: cash is received in Year 2, but news about that cash arrives in Year 1.</p>
<div class="a11y-table-region" role="region" tabindex="0" aria-label="Scrollable data table">
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Time</th>
<th>Cash and information</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>Buy asset; everyone assigns 50% to each Year 2 state.</td>
</tr>
<tr class="even">
<td>End of Year 1</td>
<td>Receive and distribute $660; observe the state.</td>
</tr>
<tr class="odd">
<td>End of Year 2</td>
<td>Receive and distribute the now-known $880 or $440; asset expires.</td>
</tr>
</tbody>
</table>
</div>
<p>At time 0, valuation is</p>
<p><span class="math display">\[
V_0=\frac{660}{1.10}+\frac{0.5(880)+0.5(440)}{(1.10)^2}
=1{,}145.45.
\]</span></p>
<p>This is the same initial value as in the certainty case. We held the expected cash flows constant and assumed risk neutrality. Uncertainty alone has not reduced the price under these assumptions.</p>
</section>
<section id="separate-the-passage-of-time-from-news" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="separate-the-passage-of-time-from-news"><span class="header-section-number">3.4</span> Separate the passage of time from news</h2>
<p>At the end of Year 1, <strong>after paying out the first receipt but just before learning the state</strong>, only the Year 2 claim remains. Its expected value is $660/1.10 = $600. There is no retained cash to add. At the same date, immediately after revelation:</p>
<p><span class="math display">\[
V_{1,H}=\frac{880}{1.10}=800,
\qquad
V_{1,L}=\frac{440}{1.10}=400.
\]</span></p>
<p>The state changes the remaining asset value by +$200 or −$200 relative to the $600 expectation. First-year income includes that surprise:</p>
<div class="a11y-table-region" role="region" tabindex="0" aria-label="Scrollable data table">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Year 1 item</th>
<th style="text-align: right;">High state</th>
<th style="text-align: right;">Low state</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Expected income from opening value × 10%</td>
<td style="text-align: right;">$114.55</td>
<td style="text-align: right;">$114.55</td>
</tr>
<tr class="even">
<td>Unexpected change in remaining value</td>
<td style="text-align: right;">+200.00</td>
<td style="text-align: right;">−200.00</td>
</tr>
<tr class="odd">
<td><strong>Realized economic income</strong></td>
<td style="text-align: right;"><strong>$314.55</strong></td>
<td style="text-align: right;"><strong>−$85.45</strong></td>
</tr>
</tbody>
</table>
</div>
<p>Verify using distributions plus the change in value:</p>
<p><span class="math display">\[
I_{1,H}=660+800-1{,}145.45=314.55,
\]</span></p>
<p><span class="math display">\[
I_{1,L}=660+400-1{,}145.45=-85.45.
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled" title="A repeatable method">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
A repeatable method
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Mark the reporting date and list what is known <strong>then</strong>. Do not import news that arrives later.</li>
<li>Value only the remaining cash flows, using their probabilities given that information. After the state is revealed here, the appropriate probability is 1 for the revealed outcome.</li>
<li>Add any cash retained by the enterprise to find total ending value. Keep cash paid to owners separate.</li>
<li>Calculate income as distributions plus ending value minus beginning value. To identify news, compare the remaining asset’s values immediately before and after the report <strong>at the same date</strong>.</li>
</ol>
<p>Comparing 800 or 400 with the opening 1,145.45 would mix news with a year’s operations and passage of time.</p>
</div>
</div>
<p>Expected first-year income, assessed at time 0, remains $114.55 because the positive and negative surprises average to zero. The expected value of an unexpected gain or loss is zero relative to the information used to form the expectation; realized gains and losses need not be zero.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Cash arrived, but there is a loss">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Cash arrived, but there is a loss
</div>
</div>
<div class="callout-body-container callout-body">
<p>In the low state, Campus Curb receives $660 and reports an economic loss. The bad news about the remaining asset more than offsets the expected return. Cash received this year does not summarize everything learned about future receipts.</p>
</div>
</div>
</section>
<section id="accounting-for-the-state-revelation" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="accounting-for-the-state-revelation"><span class="header-section-number">3.5</span> Accounting for the state revelation</h2>
<p>Here is a present-value income statement that separates the two components. We use expected economic depreciation of $545.45 before the state revision, then record the unexpected remeasurement separately.</p>
<div class="a11y-table-region" role="region" tabindex="0" aria-label="Scrollable data table">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Year 1 income statement</th>
<th style="text-align: right;">High</th>
<th style="text-align: right;">Low</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Net operating receipts</td>
<td style="text-align: right;">$660.00</td>
<td style="text-align: right;">$660.00</td>
</tr>
<tr class="even">
<td>Expected economic depreciation</td>
<td style="text-align: right;">(545.45)</td>
<td style="text-align: right;">(545.45)</td>
</tr>
<tr class="odd">
<td>Gain/(loss) from new information</td>
<td style="text-align: right;">200.00</td>
<td style="text-align: right;">(200.00)</td>
</tr>
<tr class="even">
<td><strong>Economic income/(loss)</strong></td>
<td style="text-align: right;"><strong>$314.55</strong></td>
<td style="text-align: right;"><strong>($85.45)</strong></td>
</tr>
</tbody>
</table>
</div>
<div class="a11y-table-region" role="region" tabindex="0" aria-label="Scrollable data table">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Closing balances and equity reconciliation</th>
<th style="text-align: right;">High</th>
<th style="text-align: right;">Low</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Opening equity</td>
<td style="text-align: right;">$1,145.45</td>
<td style="text-align: right;">$1,145.45</td>
</tr>
<tr class="even">
<td>Income/(loss)</td>
<td style="text-align: right;">314.55</td>
<td style="text-align: right;">(85.45)</td>
</tr>
<tr class="odd">
<td>Distribution</td>
<td style="text-align: right;">(660.00)</td>
<td style="text-align: right;">(660.00)</td>
</tr>
<tr class="even">
<td><strong>Closing equity</strong></td>
<td style="text-align: right;"><strong>$800.00</strong></td>
<td style="text-align: right;"><strong>$400.00</strong></td>
</tr>
<tr class="odd">
<td>Closing cash</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td>Closing delivery asset</td>
<td style="text-align: right;">800.00</td>
<td style="text-align: right;">400.00</td>
</tr>
<tr class="odd">
<td>Closing liabilities</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
</tr>
</tbody>
</table>
</div>
<p>The cash-flow statement is identical in both states: $660 from operations, $660 distributed, and no net change in cash. The balance sheet and income statement differ because the same cash receipt accompanies different news.</p>
<p>In Year 2 there is no further surprise. Income is $80 in the high state or $40 in the low state, each 10% of the corresponding opening value. Lifetime income is $394.55 in the high state and −$45.45 in the low state. Check those totals by subtracting the initial investment from lifetime cash distributions. Their average is the certainty case’s $174.55.</p>
<p>These are statements under a stipulated measurement model. Whether GAAP recognizes a particular forecast revision, and where, depends on the relevant accounting requirements. Economic news is not automatically a GAAP entry.</p>
</section>
<section id="expected-loss-is-not-the-same-as-a-price-of-risk" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="expected-loss-is-not-the-same-as-a-price-of-risk"><span class="header-section-number">3.6</span> Expected loss is not the same as a price of risk</h2>
<p>Consider three claims paying in two years, discounted at 5% with risk-neutral investors:</p>
<div class="a11y-table-region" role="region" tabindex="0" aria-label="Scrollable data table">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Payoff</th>
<th style="text-align: right;">Expected payoff</th>
<th style="text-align: right;">Present value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Certain $1,000</td>
<td style="text-align: right;">$1,000</td>
<td style="text-align: right;">$907.03</td>
</tr>
<tr class="even">
<td>Equal chances of $500 and $1,500</td>
<td style="text-align: right;">$1,000</td>
<td style="text-align: right;">$907.03</td>
</tr>
<tr class="odd">
<td>90% chance of $1,000; 10% chance of zero</td>
<td style="text-align: right;">$900</td>
<td style="text-align: right;">$816.33</td>
</tr>
</tbody>
</table>
</div>
<p>The third claim is worth $90.70 less than the first because its expected receipt is $100 lower. This is the present value of expected nonpayment. It does not isolate a separate “cost of not knowing.”</p>
<p>Outside our risk-neutral model, investors may demand compensation for bearing priced risk. Which risks affect market prices depends on the economic setting, including how payoffs co-vary with other risks investors bear. Greater variation by itself is not a complete asset-pricing theory.</p>
<p>For this unit, use the supplied risk-neutral assumption. In a later valuation using risk adjustment, explain whether risk is handled in the cash flows, discount rate, or state prices. Do not add a second adjustment for the same risk without examining what the first already includes. We need a consistent model, not a rule that “uncertainty always subtracts value.”</p>
</section>
<section id="a-useful-report-can-deliver-bad-news" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="a-useful-report-can-deliver-bad-news"><span class="header-section-number">3.7</span> A useful report can deliver bad news</h2>
<p>In the low state, disclosing the news reduces the remaining asset’s value from its prior expectation of $600 to $400. The report has not destroyed a $200 physical resource. It has changed what users know about an already-existing economic situation.</p>
<p>That distinction matters when interpreting evidence. A negative price response does not establish that disclosure was socially harmful. Conversely, an announcement followed by a price increase does not prove that the reporting rule created wealth. Users may simply have learned good news.</p>
<p>The question becomes sharper when users must choose an action. Would a lender offer the same amount after learning the low state? Would a prospective investor buy at the seller’s proposed price? In the next chapter we make the report imperfect and ask how much a decision maker would pay for it.</p>
</section>
<section id="evidence-habits-prediction-is-not-proof" class="level2" data-number="3.8">
<h2 data-number="3.8" class="anchored" data-anchor-id="evidence-habits-prediction-is-not-proof"><span class="header-section-number">3.8</span> Evidence habits: prediction is not proof</h2>
<p>This week’s numerical cases are constructed models, not empirical findings. You can verify their arithmetic exactly because their assumptions are specified. A study of real companies faces additional questions: how to measure expectations, when information became available, and what else happened at the same time.</p>
<p>Write two sentences before seeing data: one stating the model’s prediction, and another describing a result that would make you question its application. This habit prepares you for the earnings-announcement evidence in <a href="../arc2-markets/06-efficient-markets.html" class="quarto-xref"><span>Chapter 6</span></a>. A model that can “explain” every possible outcome after the fact has not supplied a useful test.</p>
</section>
<section id="check-your-understanding" class="level2" data-number="3.9">
<h2 data-number="3.9" class="anchored" data-anchor-id="check-your-understanding"><span class="header-section-number">3.9</span> Check your understanding</h2>
<p>If the state is revealed only in Year 2, and no other news arrives in Year 1, the Year 1 closing expected asset value remains $600. Explain why the timing of information changes the timing of remeasurement income, even though the ultimate cash outcomes are unchanged. Then work the drills.</p>
<p>Before the drills, change just the payout in the original high-state case: keep the $660 receipt as cash until the reporting instant instead of distributing it. What are total assets and income? Does retaining cash remove the news component?</p>
<div class="callout callout-style-default callout-note callout-titled" title="Check timing and retained cash">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check timing and retained cash
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>With delayed revelation, income is $660 + $600 − $1,145.45 = $114.55. There is no state news yet, so do not use the eventual 800 or 400 early.</p>
<p>With high-state revelation and retained cash, assets are $660 cash + $800 remaining claim = $1,460. Distributions are zero, so income is still $314.55. The news component remains +$200; retaining the receipt changes where the owner’s wealth sits, not what was learned about the final payment.</p>
</div>
</div>
</div>
<p><a href="../drills/pdf/wk03-drills.pdf">Printable drill sheet</a> · <a href="../drills/pdf/wk03-drills-key.pdf">Self-check key</a></p>
</section>
<section id="sec-drill-wk03" class="level2" data-number="3.10">
<h2 data-number="3.10" class="anchored" data-anchor-id="sec-drill-wk03"><span class="header-section-number">3.10</span> Week 3 drills: uncertainty and news</h2>
<p>Use the stated risk-neutral model and a calculator. Complete after Day 5 and submit before Day 6; check and correct your work. Graded for completion; no generative AI.</p>
<ol type="1">
<li>A claim pays $154 or $88 in one year, each with probability 0.5. Calculate expected cash and value at 10%. Compare with a certain $121 payment on the same date.</li>
<li>An all-equity enterprise distributes $110 at the end of Year 1 and either $154 or $88 at the end of Year 2, with equal prior probabilities. The rate is 10%. The state is perfectly revealed at the end of Year 1. There is no terminal asset value, no debt, and no further investment. Calculate (a) initial value, (b) Year 1 closing asset and equity in each state, (c) Year 1 income in each state, (d) expected Year 1 income assessed at acquisition, and (e) the expected-return and news components of each outcome.</li>
<li>If Problem 2’s state is revealed only in Year 2 and no other news arrives in Year 1, what are Year 1 closing value and income? Explain what moved to a later period.</li>
<li>At 5% for two years, compare a certain $1,000 with a 90% chance of $1,000 and a 10% chance of zero. How much value is lost? What change in the assumptions accounts for the difference in this calculation?</li>
<li>An unbiased forecasting process sometimes produces estimates above realized cash and sometimes below. Does one low realization establish manipulation? State one piece of evidence you would seek about the original estimate.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Drill answers">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Drill answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Expected cash = <strong>$121</strong>; value = <strong>$110</strong>. The certain claim also has value $110 under the supplied assumptions.</li>
<li><ol type="a">
<li>110/1.10 + 121/1.10² = <strong>$200</strong>. (b) High <strong>$140</strong>, low <strong>$80</strong>, for both the remaining asset and equity; closing cash and liabilities are zero. (c) High income = 110 + 140 − 200 = <strong>$50</strong>; low = 110 + 80 − 200 = <strong>−$10</strong>. (d) <strong>$20</strong>. (e) Expected return <strong>$20</strong> in both states; news is <strong>+$30</strong> or <strong>−$30</strong>. First-year cash flows are the same in both states.</li>
</ol></li>
<li>Closing value <strong>$110</strong>, income <strong>$20</strong>. With no Year 1 news, the state-dependent revision is postponed; ultimate operating cash flows are not changed.</li>
<li>Values <strong>$907.03</strong> and <strong>$816.33</strong>; difference <strong>$90.70</strong>. Expected cash falls from $1,000 to $900. This is a discounted expected-payoff reduction, not an isolated risk premium or value of information.</li>
<li><strong>No.</strong> Seek information available at the estimate date, model assumptions, evidence of bias, or consistent application. Do not judge solely with hindsight.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="optional-extension-uncertain-probabilities" class="level2" data-number="3.11">
<h2 data-number="3.11" class="anchored" data-anchor-id="optional-extension-uncertain-probabilities"><span class="header-section-number">3.11</span> Optional extension: uncertain probabilities</h2>
<p>We have assumed that everyone knows the probabilities. What if founders estimate a 70% chance of high demand and an outside analyst estimates 40%? The disagreement might reflect different evidence, different models, or biased reporting. It need not mean one person is lying.</p>
<p>Compute both valuations, holding everything else fixed. Identify the evidence you would need to distinguish an informed estimate from an optimistic one. This introduces a measurement problem we will return to when discussing faithful representation.</p>


<!-- -->

</section>

</main> <!-- /main -->
<footer class="course-accessibility"><p><a href="https://www.psu.edu/accessibilitystatement">Penn State accessibility statement</a> · <a href="mailto:accessibility@psu.edu">Report an accessibility barrier to the Penn State IT Accessibility Team</a>. Include the page address and a description of the issue.</p></footer>
<script>
document.addEventListener('DOMContentLoaded', function () {
  document.querySelectorAll('main table').forEach(function (table) {
    table.querySelectorAll('thead th').forEach(function (th) { th.scope = 'col'; });
    table.querySelectorAll('tbody tr').forEach(function (row) {
      var first = row.firstElementChild;
      if (first && first.tagName === 'TD' && first.textContent.trim()) {
        var th = document.createElement('th');
        th.scope = 'row'; th.innerHTML = first.innerHTML;
        th.style.cssText = first.style.cssText; th.style.fontWeight = 'normal';
        first.replaceWith(th);
      }
    });
    var region = table.closest('.a11y-table-region');
    if (region && region.getAttribute('aria-label') === 'Scrollable data table') {
      var section = table.closest('section');
      var heading = section && section.querySelector('h1,h2,h3,h4,h5,h6');
      if (heading) region.setAttribute('aria-label', heading.textContent.trim() + ' — data table');
    }
  });
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/sbb151\.github\.io\/acctg211h-companion\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../arc1-information/02-certainty.html" class="pagination-link" aria-label="Value and Income Under Certainty">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Value and Income Under Certainty</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../arc1-information/04-information-incentives.html" class="pagination-link" aria-label="Information, Credibility, and Incentives">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Information, Credibility, and Incentives</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Separate expected income from news, expected losses from priced risk, and shared uncertainty from unequal information."</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu"># Value and Income Under Uncertainty {#sec-uncertainty}</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="Your route through this chapter"}</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>**Week 3 · Required:** the main text and Week 3 drills. Read through *The same enterprise with an uncertain final receipt* and answer reading questions 1–3 before the first meeting; finish the main text and questions 4–5 before the second. Allow 45–60 minutes for text and worked examples, plus 20 minutes for drills. Review @eq-economic-income if the distribution/value distinction is unfamiliar.</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>You should be able to compute expected payoffs, value our simplified uncertain enterprise, reconcile statements after news, and explain why a lower expected payoff is different from a risk premium. No calculus or statistical software is required.</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- company-context-start --&gt;</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Tesla and Rivian connection"}</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>Use <span class="co">[</span><span class="ot">the Chapter 3 company prompt</span><span class="co">](../appendices/a04-tesla-rivian.qmd#company-c03)</span> when directed in class. Reported facts and constructed assumptions are labeled separately; this connection adds no separate submission.</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- company-context-end --&gt;</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="fu">## An uncertain outcome need not be private information</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>Campus Curb's founders and investors might agree on the possible outcomes and their probabilities without knowing which will occur. This is uncertainty with **symmetric information**. It is different from a manager concealing a fact already known to her.</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>In this chapter, everyone shares the same probability model. Investors are **risk neutral**: for the payoffs considered here they value an uncertain dollar amount at its expected amount before discounting for time. They can borrow and lend at the stated interest rate, and we retain the other simplifying assumptions from @sec-certainty. These assumptions let us introduce uncertainty without simultaneously introducing a pricing model for risk or a credibility problem.</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>Risk neutrality is a teaching assumption. It does not mean that real investors are indifferent to all risks or that a risky investment should always be discounted at the risk-free rate.</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="fu">## An expected value is a weighted average</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>Suppose a claim pays \$880 in a high-demand state and \$440 in a low-demand state. Each state has probability 0.5. Its **expected payoff** is</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>E<span class="co">[</span><span class="ot">X</span><span class="co">]</span>=0.5(880)+0.5(440)=660.</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>The weights sum to one. They describe our uncertainty, not a promise to receive part of each outcome. The actual receipt will be \$880 or \$440; it will never be \$660 in this example. An expectation can be useful even though it is not a possible realization.</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>A report that estimates \$660 has not necessarily made an error when the outcome is \$440. To judge the estimate, ask what information was available when it was made, whether the probability model was appropriate, and whether that model was applied honestly and correctly. A single unfavorable outcome cannot answer all those questions.</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="fu">## The same enterprise with an uncertain final receipt</span></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>Return to the Campus Curb model enterprise. Keep Year 1's net cash receipt of \$660 certain. Year 2's receipt is now \$880 or \$440, with equal probability. The annual rate remains 10%, the asset has no value after Year 2, all cash receipts are immediately distributed, and there is no debt. At acquisition, everyone knows this distribution.</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>At the **end of Year 1**, just after the first receipt and distribution, the demand state is publicly revealed. After revelation, the appropriate Year 2 receipt is known with certainty. This timing is essential: cash is received in Year 2, but news about that cash arrives in Year 1.</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>| Time | Cash and information |</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>|---|---|</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>| 0 | Buy asset; everyone assigns 50% to each Year 2 state. |</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>| End of Year 1 | Receive and distribute \$660; observe the state. |</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>| End of Year 2 | Receive and distribute the now-known \$880 or \$440; asset expires. |</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>At time 0, valuation is</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>V_0=\frac{660}{1.10}+\frac{0.5(880)+0.5(440)}{(1.10)^2}</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>=1{,}145.45.</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>This is the same initial value as in the certainty case. We held the expected cash flows constant and assumed risk neutrality. Uncertainty alone has not reduced the price under these assumptions.</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a><span class="fu">## Separate the passage of time from news</span></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>At the end of Year 1, **after paying out the first receipt but just before learning the state**, only the Year 2 claim remains. Its expected value is \$660/1.10 = \$600. There is no retained cash to add. At the same date, immediately after revelation:</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>V_{1,H}=\frac{880}{1.10}=800,</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>\qquad</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>V_{1,L}=\frac{440}{1.10}=400.</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>The state changes the remaining asset value by +\$200 or −\$200 relative to the \$600 expectation. First-year income includes that surprise:</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>| Year 1 item | High state | Low state |</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>|---|---:|---:|</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>| Expected income from opening value × 10% | \$114.55 | \$114.55 |</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>| Unexpected change in remaining value | +200.00 | −200.00 |</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>| **Realized economic income** | **\$314.55** | **−\$85.45** |</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>Verify using distributions plus the change in value:</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>I_{1,H}=660+800-1{,}145.45=314.55,</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>I_{1,L}=660+400-1{,}145.45=-85.45.</span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="A repeatable method"}</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Mark the reporting date and list what is known **then**. Do not import news that arrives later.</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Value only the remaining cash flows, using their probabilities given that information. After the state is revealed here, the appropriate probability is 1 for the revealed outcome.</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Add any cash retained by the enterprise to find total ending value. Keep cash paid to owners separate.</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Calculate income as distributions plus ending value minus beginning value. To identify news, compare the remaining asset's values immediately before and after the report **at the same date**.</span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a>Comparing 800 or 400 with the opening 1,145.45 would mix news with a year's operations and passage of time.</span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>Expected first-year income, assessed at time 0, remains \$114.55 because the positive and negative surprises average to zero. The expected value of an unexpected gain or loss is zero relative to the information used to form the expectation; realized gains and losses need not be zero.</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>::: {.callout-warning title="Cash arrived, but there is a loss"}</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>In the low state, Campus Curb receives \$660 and reports an economic loss. The bad news about the remaining asset more than offsets the expected return. Cash received this year does not summarize everything learned about future receipts.</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a><span class="fu">## Accounting for the state revelation</span></span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>Here is a present-value income statement that separates the two components. We use expected economic depreciation of \$545.45 before the state revision, then record the unexpected remeasurement separately.</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>| Year 1 income statement | High | Low |</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a>|---|---:|---:|</span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>| Net operating receipts | \$660.00 | \$660.00 |</span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a>| Expected economic depreciation | (545.45) | (545.45) |</span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a>| Gain/(loss) from new information | 200.00 | (200.00) |</span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a>| **Economic income/(loss)** | **\$314.55** | **(\$85.45)** |</span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a>| Closing balances and equity reconciliation | High | Low |</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a>|---|---:|---:|</span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>| Opening equity | \$1,145.45 | \$1,145.45 |</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a>| Income/(loss) | 314.55 | (85.45) |</span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a>| Distribution | (660.00) | (660.00) |</span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>| **Closing equity** | **\$800.00** | **\$400.00** |</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a>| Closing cash | 0.00 | 0.00 |</span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a>| Closing delivery asset | 800.00 | 400.00 |</span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a>| Closing liabilities | 0.00 | 0.00 |</span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>The cash-flow statement is identical in both states: \$660 from operations, \$660 distributed, and no net change in cash. The balance sheet and income statement differ because the same cash receipt accompanies different news.</span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>In Year 2 there is no further surprise. Income is \$80 in the high state or \$40 in the low state, each 10% of the corresponding opening value. Lifetime income is \$394.55 in the high state and −\$45.45 in the low state. Check those totals by subtracting the initial investment from lifetime cash distributions. Their average is the certainty case's \$174.55.</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a>These are statements under a stipulated measurement model. Whether GAAP recognizes a particular forecast revision, and where, depends on the relevant accounting requirements. Economic news is not automatically a GAAP entry.</span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a><span class="fu">## Expected loss is not the same as a price of risk</span></span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a>Consider three claims paying in two years, discounted at 5% with risk-neutral investors:</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a>| Payoff | Expected payoff | Present value |</span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a>|---|---:|---:|</span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a>| Certain \$1,000 | \$1,000 | \$907.03 |</span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a>| Equal chances of \$500 and \$1,500 | \$1,000 | \$907.03 |</span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a>| 90% chance of \$1,000; 10% chance of zero | \$900 | \$816.33 |</span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>The third claim is worth \$90.70 less than the first because its expected receipt is \$100 lower. This is the present value of expected nonpayment. It does not isolate a separate “cost of not knowing.”</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>Outside our risk-neutral model, investors may demand compensation for bearing priced risk. Which risks affect market prices depends on the economic setting, including how payoffs co-vary with other risks investors bear. Greater variation by itself is not a complete asset-pricing theory.</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>For this unit, use the supplied risk-neutral assumption. In a later valuation using risk adjustment, explain whether risk is handled in the cash flows, discount rate, or state prices. Do not add a second adjustment for the same risk without examining what the first already includes. We need a consistent model, not a rule that “uncertainty always subtracts value.”</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a><span class="fu">## A useful report can deliver bad news</span></span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a>In the low state, disclosing the news reduces the remaining asset's value from its prior expectation of \$600 to \$400. The report has not destroyed a \$200 physical resource. It has changed what users know about an already-existing economic situation.</span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a>That distinction matters when interpreting evidence. A negative price response does not establish that disclosure was socially harmful. Conversely, an announcement followed by a price increase does not prove that the reporting rule created wealth. Users may simply have learned good news.</span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a>The question becomes sharper when users must choose an action. Would a lender offer the same amount after learning the low state? Would a prospective investor buy at the seller's proposed price? In the next chapter we make the report imperfect and ask how much a decision maker would pay for it.</span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a><span class="fu">## Evidence habits: prediction is not proof</span></span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a>This week's numerical cases are constructed models, not empirical findings. You can verify their arithmetic exactly because their assumptions are specified. A study of real companies faces additional questions: how to measure expectations, when information became available, and what else happened at the same time.</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a>Write two sentences before seeing data: one stating the model's prediction, and another describing a result that would make you question its application. This habit prepares you for the earnings-announcement evidence in @sec-emh. A model that can “explain” every possible outcome after the fact has not supplied a useful test.</span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a><span class="fu">## Check your understanding</span></span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a>If the state is revealed only in Year 2, and no other news arrives in Year 1, the Year 1 closing expected asset value remains \$600. Explain why the timing of information changes the timing of remeasurement income, even though the ultimate cash outcomes are unchanged. Then work the drills.</span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a>Before the drills, change just the payout in the original high-state case: keep the \$660 receipt as cash until the reporting instant instead of distributing it. What are total assets and income? Does retaining cash remove the news component?</span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="Check timing and retained cash" collapse="true"}</span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a>With delayed revelation, income is \$660 + \$600 − \$1,145.45 = \$114.55. There is no state news yet, so do not use the eventual 800 or 400 early.</span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a>With high-state revelation and retained cash, assets are \$660 cash + \$800 remaining claim = \$1,460. Distributions are zero, so income is still \$314.55. The news component remains +\$200; retaining the receipt changes where the owner's wealth sits, not what was learned about the final payment.</span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Printable drill sheet</span><span class="co">](../drills/pdf/wk03-drills.pdf)</span> · <span class="co">[</span><span class="ot">Self-check key</span><span class="co">](../drills/pdf/wk03-drills-key.pdf)</span></span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a>{{&lt; include ../drills/drill-wk03.qmd &gt;}}</span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="Drill answers" collapse="true"}</span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a>{{&lt; include ../drills/key-wk03.qmd &gt;}}</span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a><span class="fu">## Optional extension: uncertain probabilities</span></span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a>We have assumed that everyone knows the probabilities. What if founders estimate a 70% chance of high demand and an outside analyst estimates 40%? The disagreement might reflect different evidence, different models, or biased reporting. It need not mean one person is lying.</span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a>Compute both valuations, holding everything else fixed. Identify the evidence you would need to distinguish an informed estimate from an optimistic one. This introduces a measurement problem we will return to when discussing faithful representation.</span></code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/sbb151/acctg211h-companion/edit/main/arc1-information/03-uncertainty.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/sbb151/acctg211h-companion/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>