<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Learn from noisy reports, distinguish disclosure from costly signaling, and evaluate performance when outcomes mix effort and luck.">

<title>4&nbsp; Information, Credibility, and Incentives – ACCTG 211H Companion</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../arc1-information/05-framework.html" rel="next">
<link href="../arc1-information/03-uncertainty.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../accessibility/course.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../arc1-information/01-information.html">Arc I — Information, Value, and Reporting</a></li><li class="breadcrumb-item"><a href="../arc1-information/04-information-incentives.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Information, Credibility, and Incentives</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">ACCTG 211H Companion</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/sbb151/acctg211h-companion" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface: Reading, Practice, and Evidence</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Arc I — Information, Value, and Reporting</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc1-information/01-information.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Why Accounting? Information and Cooperation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc1-information/02-certainty.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Value and Income Under Certainty</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc1-information/03-uncertainty.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Value and Income Under Uncertainty</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc1-information/04-information-incentives.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Information, Credibility, and Incentives</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc1-information/05-framework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">From Economic Questions to Accounting Reports</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Arc II — Markets and Measurement</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc2-markets/06-efficient-markets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Efficient Markets and the Information Content of Earnings</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc2-markets/07-accruals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Cash Flows, Accruals, and Earnings Quality</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc2-markets/08-long-term-assets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Long-Term Assets and Measurement Choice</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc2-markets/09-liabilities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Liabilities, Debt Covenants, and Conservatism</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc2-markets/10-equity-compensation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Equity, Compensation, and Reporting Incentives</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Arc III — Contracting and Internal Information</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc3-internal/11-decentralization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Decentralization and Cost Behavior</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc3-internal/12-performance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Performance Measurement as Agency</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc3-internal/13-capital-budgeting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Capital Budgeting Under Asymmetric Information</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Arc IV — Synthesis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc4-synthesis/14-debates.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Synthesis: The Capstone Debates</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/a01-fset.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">A1. The Financial Statement Effects Template</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/a02-python-wrds-colab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">A2. Python + WRDS in Google Colab Quickstart</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/a03-debits-credits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">A3. Debits and Credits</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/a04-tesla-rivian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Tesla and Rivian: Company Connections</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-report-does-not-reveal-everything" id="toc-the-report-does-not-reveal-everything" class="nav-link active" data-scroll-target="#the-report-does-not-reveal-everything"><span class="header-section-number">4.1</span> The report does not reveal everything</a></li>
  <li><a href="#update-with-counts-before-using-a-formula" id="toc-update-with-counts-before-using-a-formula" class="nav-link" data-scroll-target="#update-with-counts-before-using-a-formula"><span class="header-section-number">4.2</span> Update with counts before using a formula</a>
  <ul class="collapse">
  <li><a href="#from-a-report-to-value-and-income" id="toc-from-a-report-to-value-and-income" class="nav-link" data-scroll-target="#from-a-report-to-value-and-income">From a report to value and income</a></li>
  </ul></li>
  <li><a href="#how-much-is-information-worth-for-a-decision" id="toc-how-much-is-information-worth-for-a-decision" class="nav-link" data-scroll-target="#how-much-is-information-worth-for-a-decision"><span class="header-section-number">4.3</span> How much is information worth for a decision?</a></li>
  <li><a href="#sec-signaling" id="toc-sec-signaling" class="nav-link" data-scroll-target="#sec-signaling"><span class="header-section-number">4.4</span> Who produces the report, and why believe it?</a>
  <ul class="collapse">
  <li><a href="#why-silence-can-be-informative" id="toc-why-silence-can-be-informative" class="nav-link" data-scroll-target="#why-silence-can-be-informative">Why silence can be informative</a></li>
  <li><a href="#what-makes-a-reporting-process-credible" id="toc-what-makes-a-reporting-process-credible" class="nav-link" data-scroll-target="#what-makes-a-reporting-process-credible">What makes a reporting process credible?</a></li>
  </ul></li>
  <li><a href="#valuation-and-stewardship-ask-different-questions" id="toc-valuation-and-stewardship-ask-different-questions" class="nav-link" data-scroll-target="#valuation-and-stewardship-ask-different-questions"><span class="header-section-number">4.5</span> Valuation and stewardship ask different questions</a></li>
  <li><a href="#check-your-understanding" id="toc-check-your-understanding" class="nav-link" data-scroll-target="#check-your-understanding"><span class="header-section-number">4.6</span> Check your understanding</a></li>
  <li><a href="#sec-drill-wk04" id="toc-sec-drill-wk04" class="nav-link" data-scroll-target="#sec-drill-wk04"><span class="header-section-number">4.7</span> Week 4 drills: information and incentives</a></li>
  <li><a href="#optional-extension-a-costly-signal-is-not-a-free-improvement" id="toc-optional-extension-a-costly-signal-is-not-a-free-improvement" class="nav-link" data-scroll-target="#optional-extension-a-costly-signal-is-not-a-free-improvement"><span class="header-section-number">4.8</span> Optional extension: a costly signal is not a free improvement</a></li>
  <li><a href="#optional-extension-the-len-model" id="toc-optional-extension-the-len-model" class="nav-link" data-scroll-target="#optional-extension-the-len-model"><span class="header-section-number">4.9</span> Optional extension: the LEN model</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/sbb151/acctg211h-companion/edit/main/arc1-information/04-information-incentives.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/sbb151/acctg211h-companion/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../arc1-information/01-information.html">Arc I — Information, Value, and Reporting</a></li><li class="breadcrumb-item"><a href="../arc1-information/04-information-incentives.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Information, Credibility, and Incentives</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-stewardship" class="quarto-section-identifier"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Information, Credibility, and Incentives</span></span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note callout-titled" title="Your route through this chapter">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Your route through this chapter
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Week 4 · Required:</strong> the main text through <em>Check your understanding</em> and Week 4 drills. Allow 45–60 minutes for reading and examples, plus 20 minutes for drills. A frequency table supplies the probability reasoning. The Spence and LEN extensions are optional and are not assessed in Quiz 1.</p>
<p>Quiz 1 remains at the beginning of Day 8 and covers the required material in Chapters 1–3. This chapter’s Bayesian updating and incentive calculations are practiced this week and assessed later.</p>
</div>
</div>
<!-- company-context-start -->
<div class="callout callout-style-default callout-tip callout-titled" title="Tesla and Rivian connection">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tesla and Rivian connection
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use <a href="../appendices/a04-tesla-rivian.html#company-c04">the Chapter 4 company prompt</a> when directed in class. Reported facts and constructed assumptions are labeled separately; this connection adds no separate submission.</p>
</div>
</div>
<!-- company-context-end -->
<section id="the-report-does-not-reveal-everything" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="the-report-does-not-reveal-everything"><span class="header-section-number">4.1</span> The report does not reveal everything</h2>
<p>In <a href="03-uncertainty.html" class="quarto-xref"><span>Chapter 3</span></a>, everyone learned the demand state perfectly at the end of Year 1. Now change that assumption. The true state remains unknown until Year 2, but a diagnostic report arrives at the end of Year 1. Keep the same cash flows: $660 in Year 1 and either $880 or $440 in Year 2, with equal prior probabilities. Retain risk neutrality and the 10% rate.</p>
<p>The report is favorable 80% of the time when demand is high. It is favorable 20% of the time when demand is low. These error rates are known to everyone. The report may be useful without being perfect.</p>
</section>
<section id="update-with-counts-before-using-a-formula" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="update-with-counts-before-using-a-formula"><span class="header-section-number">4.2</span> Update with counts before using a formula</h2>
<p>Imagine 100 equally likely cases generated by this model:</p>
<div class="a11y-table-region" role="region" tabindex="0" aria-label="Scrollable data table">
<table class="caption-top table">
<thead>
<tr class="header">
<th>True state</th>
<th style="text-align: right;">Favorable report</th>
<th style="text-align: right;">Unfavorable report</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>High demand</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">50</td>
</tr>
<tr class="even">
<td>Low demand</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">50</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: right;"><strong>50</strong></td>
<td style="text-align: right;"><strong>50</strong></td>
<td style="text-align: right;"><strong>100</strong></td>
</tr>
</tbody>
</table>
</div>
<p>Before receiving a report, 50 of 100 cases are high: the <strong>prior probability</strong> is 50%. After a favorable report, focus on the favorable column. Forty of its 50 cases are high, so the <strong>posterior probability</strong> is 80%. After an unfavorable report, only 10 of 50 cases are high, so it is 20%.</p>
<p>This is <strong>Bayesian updating</strong>: combine the starting distribution with the information conveyed by the observation. For the favorable report,</p>
<p><span class="math display">\[
P(H\mid F)=\frac{P(F\mid H)P(H)}{P(F\mid H)P(H)+P(F\mid L)P(L)}
=\frac{0.8(0.5)}{0.8(0.5)+0.2(0.5)}=0.8.
\]</span></p>
<p>The posterior equals the report’s 80% high-state detection rate here because the prior is 50% and the error rates are symmetric. It does <strong>not</strong> generally equal that rate. If high demand were rare, a favorable report could still leave substantial doubt.</p>
<section id="from-a-report-to-value-and-income" class="level3">
<h3 class="anchored" data-anchor-id="from-a-report-to-value-and-income">From a report to value and income</h3>
<p>After a favorable report, expected Year 2 cash is 0.8($880) + 0.2($440) = $792. After an unfavorable report, it is $528. Discount one year:</p>
<div class="a11y-table-region" role="region" tabindex="0" aria-label="Scrollable data table">
<table class="caption-top table">
<thead>
<tr class="header">
<th>End of Year 1</th>
<th style="text-align: right;">Favorable report</th>
<th style="text-align: right;">Unfavorable report</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Probability of high demand</td>
<td style="text-align: right;">80%</td>
<td style="text-align: right;">20%</td>
</tr>
<tr class="even">
<td>Expected Year 2 cash</td>
<td style="text-align: right;">$792</td>
<td style="text-align: right;">$528</td>
</tr>
<tr class="odd">
<td>Remaining asset value</td>
<td style="text-align: right;">$720</td>
<td style="text-align: right;">$480</td>
</tr>
<tr class="even">
<td>Revision from prior expected value of $600</td>
<td style="text-align: right;">+$120</td>
<td style="text-align: right;">−$120</td>
</tr>
<tr class="odd">
<td>Year 1 economic income</td>
<td style="text-align: right;">$234.55</td>
<td style="text-align: right;">−$5.45</td>
</tr>
</tbody>
</table>
</div>
<p>Compute income as the $660 distribution plus the new remaining value less $1,145.45 opening value. Closing cash and liabilities are zero; equity equals the remaining asset, $720 or $480. The noisy report moves value less than perfect state revelation did because some uncertainty remains.</p>
<p>This is a further version of the same model, not an additional report after the state was already revealed. Once users know the state perfectly, a noisy signal of that same state adds no information.</p>
</section>
</section>
<section id="how-much-is-information-worth-for-a-decision" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="how-much-is-information-worth-for-a-decision"><span class="header-section-number">4.3</span> How much is information worth for a decision?</h2>
<p>Consider a <strong>separate prospective investment decision at the end of Year 1</strong>. An investor can pay $700 now for a claim to the same kind of Year 2 payoff. The investor has not bought it yet and can decline. This choice is distinct from valuing the claim already owned by the model enterprise.</p>
<p>Without a report, the claim is worth $600, so the investor declines. With the noisy report, she buys only after a favorable result: $720 value minus $700 price gives $20 of expected net benefit. A favorable report occurs with probability 0.5, so the expected benefit of having the report <strong>before paying its fee</strong> is $10. An $8 fee paid at that decision date leaves $2 net benefit.</p>
<p>With perfect information she would buy only in the high state, when value is $800. The expected benefit would be 0.5($800 − $700) = $50. This is an upper comparison for the information choices in this particular decision, not a general market price for perfect information.</p>
<p>Notice why the report helps: the investor changes her action. More precise information need not change every decision. If the price were low enough that she would buy after either report, this report would have no gross decision value in the simplified setting, even though it changes her valuation.</p>
</section>
<section id="sec-signaling" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="sec-signaling"><span class="header-section-number">4.4</span> Who produces the report, and why believe it?</h2>
<p>So far the diagnostic arrives automatically with known error rates. Real reports are produced by people. Suppose the founders observe the diagnostic privately. Outsiders now face an information asymmetry, and the founders may prefer a favorable interpretation.</p>
<p>Several mechanisms need to be distinguished:</p>
<div class="a11y-table-region" role="region" tabindex="0" aria-label="Scrollable data table">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Mechanism</th>
<th>What carries information?</th>
<th>Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Routine accounting recognition</td>
<td>A transaction, obligation, or use of resources</td>
<td>Interest accumulated under a known loan contract.</td>
</tr>
<tr class="even">
<td>Estimation</td>
<td>A model applied to incomplete evidence</td>
<td>An estimate of uncollectible customer balances.</td>
</tr>
<tr class="odd">
<td>Verifiable disclosure</td>
<td>Truthful evidence that can be checked if released</td>
<td>A signed customer contract shown to an investor.</td>
</tr>
<tr class="even">
<td>Costly signaling</td>
<td>An observable action that different types have different incentives to take</td>
<td>A warranty that is more expensive for sellers of unreliable scooters.</td>
</tr>
<tr class="odd">
<td>Misstatement</td>
<td>A depiction inconsistent with the relevant facts or requirements</td>
<td>Omitting interest merely because no bill has arrived.</td>
</tr>
</tbody>
</table>
</div>
<p>A useful number need not be a costly signal. A cost by itself does not make a statement true. Equally, an estimate that later differs from the realization need not have been a misstatement.</p>
<section id="why-silence-can-be-informative" class="level3">
<h3 class="anchored" data-anchor-id="why-silence-can-be-informative">Why silence can be informative</h3>
<p>If an informed seller can disclose a value truthfully, verifiably, and without cost, favorable types want to distinguish themselves from less favorable ones. As they disclose, the remaining silent pool becomes less attractive. This is the intuition behind disclosure unraveling <span class="citation" data-cites="grossman1981 milgrom1981">(<a href="../references.html#ref-grossman1981" role="doc-biblioref">Grossman 1981</a>; <a href="../references.html#ref-milgrom1981" role="doc-biblioref">Milgrom 1981</a>)</span>.</p>
<p>Real disclosure can be incomplete because releasing information has costs or because investors do not know whether a manager possesses information <span class="citation" data-cites="verrecchia1983 dye1985">(<a href="../references.html#ref-verrecchia1983" role="doc-biblioref">Verrecchia 1983</a>; <a href="../references.html#ref-dye1985" role="doc-biblioref">Dye 1985</a>)</span>. Silence can then reflect bad news, proprietary concerns, or a lack of information. It should not automatically be read as proof of fraud or as proof that the firm is the worst type.</p>
</section>
<section id="what-makes-a-reporting-process-credible" class="level3">
<h3 class="anchored" data-anchor-id="what-makes-a-reporting-process-credible">What makes a reporting process credible?</h3>
<p>For Campus Curb, compare the founders’ unsupported sales forecast with a report that identifies the underlying orders, distinguishes cancellable orders, explains collection assumptions, and is checked by an independent party. The latter gives users more ways to evaluate the claim.</p>
<p>Internal controls can separate authorization, custody, and recordkeeping; reconciliations can expose differences; outside confirmation can test whether a balance exists. These mechanisms have costs and do not remove all judgment. Their purpose is to make relevant claims more dependable and errors more likely to be detected.</p>
</section>
</section>
<section id="valuation-and-stewardship-ask-different-questions" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="valuation-and-stewardship-ask-different-questions"><span class="header-section-number">4.5</span> Valuation and stewardship ask different questions</h2>
<p>An investor wants to know what cash flows to expect. A compensation committee also wants to know what performance reveals about management’s actions. A favorable demand shock may increase value while saying little about whether a manager worked well.</p>
<p>Use a one-period version of Campus Curb to make the distinction. A manager chooses ordinary or extra effort. Extra effort costs the manager $30 in personal effort; ordinary effort costs zero. Good operating outcomes generate $200 for the business and bad outcomes $50. The good-outcome probability is 80% with extra effort and 40% with ordinary effort. The manager is risk neutral, can accept or reject a contract, and has an outside option worth $40. Outcomes are observable; effort is not.</p>
<div class="a11y-table-region" role="region" tabindex="0" aria-label="Scrollable data table">
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 28%">
<col style="width: 28%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Contract</th>
<th style="text-align: right;">Expected manager payoff: ordinary effort</th>
<th style="text-align: right;">Expected manager payoff: extra effort</th>
<th>Chosen effort</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fixed pay of $40</td>
<td style="text-align: right;">$40</td>
<td style="text-align: right;">$40 − $30 = $10</td>
<td>Ordinary</td>
</tr>
<tr class="even">
<td>$20 base + $80 if outcome is good</td>
<td style="text-align: right;">$20 + 0.4($80) = $52</td>
<td style="text-align: right;">$20 + 0.8($80) − $30 = $54</td>
<td>Extra</td>
</tr>
</tbody>
</table>
</div>
<p>Both contracts meet the manager’s outside option at the chosen effort. The bonus changes behavior. Expected business receipts are $110 with ordinary effort and $170 with extra effort. Expected compensation is $40 under the fixed contract and $84 under the bonus contract. Expected receipts less compensation rise from $70 to $86 in this example. We compare two feasible contracts; we have not proved that the second is optimal among all contracts.</p>
<p>A bad outcome still occurs 20% of the time under extra effort. An outcome alone does not perfectly reveal an action. An additional measure—such as a maintenance log or peer benchmark—can help when it provides information about effort beyond the measures already used. This is the central intuition of Holmstrom’s informativeness principle <span class="citation" data-cites="holmstrom1979">(<a href="../references.html#ref-holmstrom1979" role="doc-biblioref">Holmstrom 1979</a>)</span>. Adding redundant metrics is not automatically helpful.</p>
</section>
<section id="check-your-understanding" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="check-your-understanding"><span class="header-section-number">4.6</span> Check your understanding</h2>
<p>Explain why the noisy report has value for the prospective investment decision; why an unfavorable report can be useful; why a fixed contractual accrual need not reveal private information; and why a manager should not automatically be blamed for every low outcome.</p>
<p><a href="../drills/pdf/wk04-drills.pdf">Printable drill sheet</a> · <a href="../drills/pdf/wk04-drills-key.pdf">Self-check key</a></p>
</section>
<section id="sec-drill-wk04" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="sec-drill-wk04"><span class="header-section-number">4.7</span> Week 4 drills: information and incentives</h2>
<p>Complete after Day 8 and submit Sunday, February 7. These topics are not on Quiz 1. Work individually, check the key, and correct errors. Graded for completion; no generative AI.</p>
<ol type="1">
<li>Among 100 cases, 25 are high demand and 75 low demand. A report is favorable in 80% of high cases and 20% of low cases. Complete a two-by-two frequency table. What fraction of favorable reports correspond to high demand? Why is the answer not 80%?</li>
<li>Return to the chapter’s 50% prior and the same report accuracy. After a favorable report, the probability of high demand is 80%. Payoffs one year later are $880 or $440. At 10%, calculate expected payoff and value after each report.</li>
<li>At that report date an investor can buy the claim for $700 or decline. Compute the report’s expected decision benefit before its fee. Should the investor purchase information costing $8? What about $11? All costs and values are at that decision date.</li>
<li>For the main text’s manager, compare fixed pay of $40 with $20 plus $80 for a good outcome. Calculate the manager’s net expected payoff under each effort choice and identify the choice. Extra effort costs $30 and raises the good-outcome probability from 40% to 80%.</li>
<li>Classify each: recognizing interest under a known contract; estimating a scooter’s useful life; offering a warranty that costs more for unreliable products; omitting interest because a bill has not arrived. Which can involve private information, and which does not require it?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Drill answers">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Drill answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>High: favorable <strong>20</strong>, unfavorable <strong>5</strong>. Low: favorable <strong>15</strong>, unfavorable <strong>60</strong>. Posterior high given favorable = 20/35 = <strong>57.14%</strong>. The prior is only 25%; a test’s detection rate is not generally the posterior probability.</li>
<li>Favorable: expected payoff <strong>$792</strong>, value <strong>$720</strong>. Unfavorable: expected payoff <strong>$528</strong>, value <strong>$480</strong>.</li>
<li>Without the report, decline ($600 value &lt; $700 price). With it, buy only after favorable news, giving expected benefit 0.5 × (720 − 700) = <strong>$10</strong>. An $8 fee leaves <strong>$2</strong>; an $11 fee leaves <strong>−$1</strong>, so decline that information offer.</li>
<li>Fixed pay: ordinary <strong>$40</strong>, extra <strong>$10</strong>; choose ordinary. Bonus: ordinary <strong>$52</strong>, extra <strong>$54</strong>; choose extra. Both chosen payoffs meet the $40 outside option. These are two feasible contracts, not proof of global optimality.</li>
<li>Respectively: <strong>routine recognition; estimation; potentially costly signaling; misstatement</strong> under the stated facts. Useful-life estimates may incorporate private knowledge; a warranty can reveal type under suitable incentives. Fixed contractual interest recognition need not involve private information.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="optional-extension-a-costly-signal-is-not-a-free-improvement" class="level2" data-number="4.8">
<h2 data-number="4.8" class="anchored" data-anchor-id="optional-extension-a-costly-signal-is-not-a-free-improvement"><span class="header-section-number">4.8</span> Optional extension: a costly signal is not a free improvement</h2>
<p>In a stripped-down Spence example <span class="citation" data-cites="spence1973">(<a href="../references.html#ref-spence1973" role="doc-biblioref">Spence 1973</a>)</span>, high-productivity workers produce 100 and low-productivity workers 60. Education <span class="math inline">\(e\)</span> costs a high type <span class="math inline">\(e\)</span> and a low type <span class="math inline">\(2e\)</span> and does not itself raise productivity. Employers pay 100 above threshold <span class="math inline">\(e^*\)</span> and 60 otherwise.</p>
<p>Separation requires <span class="math inline">\(100-e^*\ge60\)</span> and <span class="math inline">\(60\ge100-2e^*\)</span>, giving <span class="math inline">\(20\le e^*\le40\)</span>. At 20, high types net 80 and low types net 60; low types are indifferent about mimicking, so the threshold case needs the corresponding tie-breaking behavior.</p>
<p>If the high-type share is <span class="math inline">\(\lambda\)</span>, the no-signal pooling wage is <span class="math inline">\(60+40\lambda\)</span>. Low types lose from separation for every positive <span class="math inline">\(\lambda\)</span>; high types gain only when <span class="math inline">\(\lambda&lt;0.5\)</span>. The signal can sort types while using resources and redistributing pay. It is not automatically a Pareto improvement.</p>
</section>
<section id="optional-extension-the-len-model" class="level2" data-number="4.9">
<h2 data-number="4.9" class="anchored" data-anchor-id="optional-extension-the-len-model"><span class="header-section-number">4.9</span> Optional extension: the LEN model</h2>
<p>Suppose output is <span class="math inline">\(y=e+\varepsilon\)</span> with normally distributed noise of variance <span class="math inline">\(\sigma^2\)</span>, effort cost <span class="math inline">\(ke^2/2\)</span>, a risk-neutral principal, and an agent with exponential utility and absolute risk aversion <span class="math inline">\(a&gt;0\)</span>. Restrict compensation to <span class="math inline">\(w=b+\beta y\)</span> and choose the fixed payment to satisfy participation. The agent’s certainty equivalent is</p>
<p><span class="math display">\[
CE=b+\beta e-\frac{ke^2}{2}-\frac{a\beta^2\sigma^2}{2}.
\]</span></p>
<p>Optimal effort is <span class="math inline">\(e=\beta/k\)</span>. Within this linear-contract setup the optimal slope is <span class="math inline">\(\beta^*=1/(1+ak\sigma^2)\)</span>. Greater noise or risk aversion weakens incentives because performance pay imposes risk. This is a separate risk-averse extension of the simple classroom contract, not an assumption needed for the main text.</p>
<p>The next chapter asks how reporting institutions respond when estimates, evidence, and incentives all matter.</p>


<!-- -->

<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-dye1985" class="csl-entry" role="listitem">
Dye, Ronald A. 1985. <span>“Disclosure of Nonproprietary Information.”</span> <em>Journal of Accounting Research</em> 23 (1): 123–45.
</div>
<div id="ref-grossman1981" class="csl-entry" role="listitem">
Grossman, Sanford J. 1981. <span>“The Informational Role of Warranties and Private Disclosure about Product Quality.”</span> <em>Journal of Law and Economics</em> 24 (3): 461–83.
</div>
<div id="ref-holmstrom1979" class="csl-entry" role="listitem">
Holmstrom, Bengt. 1979. <span>“Moral Hazard and Observability.”</span> <em>Bell Journal of Economics</em> 10 (1): 74–91.
</div>
<div id="ref-milgrom1981" class="csl-entry" role="listitem">
Milgrom, Paul R. 1981. <span>“Good News and Bad News: Representation Theorems and Applications.”</span> <em>Bell Journal of Economics</em> 12 (2): 380–91.
</div>
<div id="ref-spence1973" class="csl-entry" role="listitem">
Spence, A. Michael. 1973. <span>“Job Market Signaling.”</span> <em>Quarterly Journal of Economics</em> 87 (3): 355–74.
</div>
<div id="ref-verrecchia1983" class="csl-entry" role="listitem">
Verrecchia, Robert E. 1983. <span>“Discretionary Disclosure.”</span> <em>Journal of Accounting and Economics</em> 5: 179–94.
</div>
</div>
</section>

</main> <!-- /main -->
<footer class="course-accessibility"><p><a href="https://www.psu.edu/accessibilitystatement">Penn State accessibility statement</a> · <a href="mailto:accessibility@psu.edu">Report an accessibility barrier to the Penn State IT Accessibility Team</a>. Include the page address and a description of the issue.</p></footer>
<script>
document.addEventListener('DOMContentLoaded', function () {
  document.querySelectorAll('main table').forEach(function (table) {
    table.querySelectorAll('thead th').forEach(function (th) { th.scope = 'col'; });
    table.querySelectorAll('tbody tr').forEach(function (row) {
      var first = row.firstElementChild;
      if (first && first.tagName === 'TD' && first.textContent.trim()) {
        var th = document.createElement('th');
        th.scope = 'row'; th.innerHTML = first.innerHTML;
        th.style.cssText = first.style.cssText; th.style.fontWeight = 'normal';
        first.replaceWith(th);
      }
    });
    var region = table.closest('.a11y-table-region');
    if (region && region.getAttribute('aria-label') === 'Scrollable data table') {
      var section = table.closest('section');
      var heading = section && section.querySelector('h1,h2,h3,h4,h5,h6');
      if (heading) region.setAttribute('aria-label', heading.textContent.trim() + ' — data table');
    }
  });
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/sbb151\.github\.io\/acctg211h-companion\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../arc1-information/03-uncertainty.html" class="pagination-link" aria-label="Value and Income Under Uncertainty">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Value and Income Under Uncertainty</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../arc1-information/05-framework.html" class="pagination-link" aria-label="From Economic Questions to Accounting Reports">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">From Economic Questions to Accounting Reports</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">aliases:</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">  - 03-signaling.html</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co">  - 04-stewardship.html</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Learn from noisy reports, distinguish disclosure from costly signaling, and evaluate performance when outcomes mix effort and luck."</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu"># Information, Credibility, and Incentives {#sec-stewardship}</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="Your route through this chapter"}</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>**Week 4 · Required:** the main text through *Check your understanding* and Week 4 drills. Allow 45–60 minutes for reading and examples, plus 20 minutes for drills. A frequency table supplies the probability reasoning. The Spence and LEN extensions are optional and are not assessed in Quiz 1.</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>Quiz 1 remains at the beginning of Day 8 and covers the required material in Chapters 1–3. This chapter's Bayesian updating and incentive calculations are practiced this week and assessed later.</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- company-context-start --&gt;</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip title="Tesla and Rivian connection"}</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>Use <span class="co">[</span><span class="ot">the Chapter 4 company prompt</span><span class="co">](../appendices/a04-tesla-rivian.qmd#company-c04)</span> when directed in class. Reported facts and constructed assumptions are labeled separately; this connection adds no separate submission.</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- company-context-end --&gt;</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="fu">## The report does not reveal everything</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>In @sec-uncertainty, everyone learned the demand state perfectly at the end of Year 1. Now change that assumption. The true state remains unknown until Year 2, but a diagnostic report arrives at the end of Year 1. Keep the same cash flows: \$660 in Year 1 and either \$880 or \$440 in Year 2, with equal prior probabilities. Retain risk neutrality and the 10% rate.</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>The report is favorable 80% of the time when demand is high. It is favorable 20% of the time when demand is low. These error rates are known to everyone. The report may be useful without being perfect.</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="fu">## Update with counts before using a formula</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>Imagine 100 equally likely cases generated by this model:</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>| True state | Favorable report | Unfavorable report | Total |</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>|---|---:|---:|---:|</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>| High demand | 40 | 10 | 50 |</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>| Low demand | 10 | 40 | 50 |</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>| **Total** | **50** | **50** | **100** |</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>Before receiving a report, 50 of 100 cases are high: the **prior probability** is 50%. After a favorable report, focus on the favorable column. Forty of its 50 cases are high, so the **posterior probability** is 80%. After an unfavorable report, only 10 of 50 cases are high, so it is 20%.</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>This is **Bayesian updating**: combine the starting distribution with the information conveyed by the observation. For the favorable report,</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>P(H\mid F)=\frac{P(F\mid H)P(H)}{P(F\mid H)P(H)+P(F\mid L)P(L)}</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>=\frac{0.8(0.5)}{0.8(0.5)+0.2(0.5)}=0.8.</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>The posterior equals the report's 80% high-state detection rate here because the prior is 50% and the error rates are symmetric. It does **not** generally equal that rate. If high demand were rare, a favorable report could still leave substantial doubt.</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a><span class="fu">### From a report to value and income</span></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>After a favorable report, expected Year 2 cash is 0.8(\$880) + 0.2(\$440) = \$792. After an unfavorable report, it is \$528. Discount one year:</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>| End of Year 1 | Favorable report | Unfavorable report |</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>|---|---:|---:|</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>| Probability of high demand | 80% | 20% |</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>| Expected Year 2 cash | \$792 | \$528 |</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>| Remaining asset value | \$720 | \$480 |</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>| Revision from prior expected value of \$600 | +\$120 | −\$120 |</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>| Year 1 economic income | \$234.55 | −\$5.45 |</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>Compute income as the \$660 distribution plus the new remaining value less \$1,145.45 opening value. Closing cash and liabilities are zero; equity equals the remaining asset, \$720 or \$480. The noisy report moves value less than perfect state revelation did because some uncertainty remains.</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>This is a further version of the same model, not an additional report after the state was already revealed. Once users know the state perfectly, a noisy signal of that same state adds no information.</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a><span class="fu">## How much is information worth for a decision?</span></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>Consider a **separate prospective investment decision at the end of Year 1**. An investor can pay \$700 now for a claim to the same kind of Year 2 payoff. The investor has not bought it yet and can decline. This choice is distinct from valuing the claim already owned by the model enterprise.</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>Without a report, the claim is worth \$600, so the investor declines. With the noisy report, she buys only after a favorable result: \$720 value minus \$700 price gives \$20 of expected net benefit. A favorable report occurs with probability 0.5, so the expected benefit of having the report **before paying its fee** is \$10. An \$8 fee paid at that decision date leaves \$2 net benefit.</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>With perfect information she would buy only in the high state, when value is \$800. The expected benefit would be 0.5(\$800 − \$700) = \$50. This is an upper comparison for the information choices in this particular decision, not a general market price for perfect information.</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>Notice why the report helps: the investor changes her action. More precise information need not change every decision. If the price were low enough that she would buy after either report, this report would have no gross decision value in the simplified setting, even though it changes her valuation.</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a><span class="fu">## Who produces the report, and why believe it? {#sec-signaling}</span></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>So far the diagnostic arrives automatically with known error rates. Real reports are produced by people. Suppose the founders observe the diagnostic privately. Outsiders now face an information asymmetry, and the founders may prefer a favorable interpretation.</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>Several mechanisms need to be distinguished:</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>| Mechanism | What carries information? | Example |</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>|---|---|---|</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>| Routine accounting recognition | A transaction, obligation, or use of resources | Interest accumulated under a known loan contract. |</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>| Estimation | A model applied to incomplete evidence | An estimate of uncollectible customer balances. |</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>| Verifiable disclosure | Truthful evidence that can be checked if released | A signed customer contract shown to an investor. |</span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a>| Costly signaling | An observable action that different types have different incentives to take | A warranty that is more expensive for sellers of unreliable scooters. |</span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>| Misstatement | A depiction inconsistent with the relevant facts or requirements | Omitting interest merely because no bill has arrived. |</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>A useful number need not be a costly signal. A cost by itself does not make a statement true. Equally, an estimate that later differs from the realization need not have been a misstatement.</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a><span class="fu">### Why silence can be informative</span></span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>If an informed seller can disclose a value truthfully, verifiably, and without cost, favorable types want to distinguish themselves from less favorable ones. As they disclose, the remaining silent pool becomes less attractive. This is the intuition behind disclosure unraveling <span class="co">[</span><span class="ot">@grossman1981; @milgrom1981</span><span class="co">]</span>.</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>Real disclosure can be incomplete because releasing information has costs or because investors do not know whether a manager possesses information <span class="co">[</span><span class="ot">@verrecchia1983; @dye1985</span><span class="co">]</span>. Silence can then reflect bad news, proprietary concerns, or a lack of information. It should not automatically be read as proof of fraud or as proof that the firm is the worst type.</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a><span class="fu">### What makes a reporting process credible?</span></span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>For Campus Curb, compare the founders' unsupported sales forecast with a report that identifies the underlying orders, distinguishes cancellable orders, explains collection assumptions, and is checked by an independent party. The latter gives users more ways to evaluate the claim.</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>Internal controls can separate authorization, custody, and recordkeeping; reconciliations can expose differences; outside confirmation can test whether a balance exists. These mechanisms have costs and do not remove all judgment. Their purpose is to make relevant claims more dependable and errors more likely to be detected.</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a><span class="fu">## Valuation and stewardship ask different questions</span></span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>An investor wants to know what cash flows to expect. A compensation committee also wants to know what performance reveals about management's actions. A favorable demand shock may increase value while saying little about whether a manager worked well.</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>Use a one-period version of Campus Curb to make the distinction. A manager chooses ordinary or extra effort. Extra effort costs the manager \$30 in personal effort; ordinary effort costs zero. Good operating outcomes generate \$200 for the business and bad outcomes \$50. The good-outcome probability is 80% with extra effort and 40% with ordinary effort. The manager is risk neutral, can accept or reject a contract, and has an outside option worth \$40. Outcomes are observable; effort is not.</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>| Contract | Expected manager payoff: ordinary effort | Expected manager payoff: extra effort | Chosen effort |</span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a>|---|---:|---:|---|</span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a>| Fixed pay of \$40 | \$40 | \$40 − \$30 = \$10 | Ordinary |</span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a>| \$20 base + \$80 if outcome is good | \$20 + 0.4(\$80) = \$52 | \$20 + 0.8(\$80) − \$30 = \$54 | Extra |</span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a>Both contracts meet the manager's outside option at the chosen effort. The bonus changes behavior. Expected business receipts are \$110 with ordinary effort and \$170 with extra effort. Expected compensation is \$40 under the fixed contract and \$84 under the bonus contract. Expected receipts less compensation rise from \$70 to \$86 in this example. We compare two feasible contracts; we have not proved that the second is optimal among all contracts.</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>A bad outcome still occurs 20% of the time under extra effort. An outcome alone does not perfectly reveal an action. An additional measure—such as a maintenance log or peer benchmark—can help when it provides information about effort beyond the measures already used. This is the central intuition of Holmstrom's informativeness principle <span class="co">[</span><span class="ot">@holmstrom1979</span><span class="co">]</span>. Adding redundant metrics is not automatically helpful.</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a><span class="fu">## Check your understanding</span></span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a>Explain why the noisy report has value for the prospective investment decision; why an unfavorable report can be useful; why a fixed contractual accrual need not reveal private information; and why a manager should not automatically be blamed for every low outcome.</span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Printable drill sheet</span><span class="co">](../drills/pdf/wk04-drills.pdf)</span> · <span class="co">[</span><span class="ot">Self-check key</span><span class="co">](../drills/pdf/wk04-drills-key.pdf)</span></span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>{{&lt; include ../drills/drill-wk04.qmd &gt;}}</span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="Drill answers" collapse="true"}</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>{{&lt; include ../drills/key-wk04.qmd &gt;}}</span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a><span class="fu">## Optional extension: a costly signal is not a free improvement</span></span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a>In a stripped-down Spence example <span class="co">[</span><span class="ot">@spence1973</span><span class="co">]</span>, high-productivity workers produce 100 and low-productivity workers 60. Education $e$ costs a high type $e$ and a low type $2e$ and does not itself raise productivity. Employers pay 100 above threshold $e^*$ and 60 otherwise.</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a>Separation requires $100-e^*\ge60$ and $60\ge100-2e^*$, giving $20\le e^*\le40$. At 20, high types net 80 and low types net 60; low types are indifferent about mimicking, so the threshold case needs the corresponding tie-breaking behavior.</span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a>If the high-type share is $\lambda$, the no-signal pooling wage is $60+40\lambda$. Low types lose from separation for every positive $\lambda$; high types gain only when $\lambda&lt;0.5$. The signal can sort types while using resources and redistributing pay. It is not automatically a Pareto improvement.</span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a><span class="fu">## Optional extension: the LEN model</span></span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>Suppose output is $y=e+\varepsilon$ with normally distributed noise of variance $\sigma^2$, effort cost $ke^2/2$, a risk-neutral principal, and an agent with exponential utility and absolute risk aversion $a&gt;0$. Restrict compensation to $w=b+\beta y$ and choose the fixed payment to satisfy participation. The agent's certainty equivalent is</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>CE=b+\beta e-\frac{ke^2}{2}-\frac{a\beta^2\sigma^2}{2}.</span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a>Optimal effort is $e=\beta/k$. Within this linear-contract setup the optimal slope is $\beta^*=1/(1+ak\sigma^2)$. Greater noise or risk aversion weakens incentives because performance pay imposes risk. This is a separate risk-averse extension of the simple classroom contract, not an assumption needed for the main text.</span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a>The next chapter asks how reporting institutions respond when estimates, evidence, and incentives all matter.</span></code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/sbb151/acctg211h-companion/edit/main/arc1-information/04-information-incentives.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/sbb151/acctg211h-companion/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>