<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Tesla and Rivian examples connecting information, statements, incentives, and investment decisions.">

<title>Appendix D — Tesla and Rivian: Company Connections – ACCTG 211H Companion</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../appendices/a03-debits-credits.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../accessibility/course.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../appendices/a01-fset.html">Appendices</a></li><li class="breadcrumb-item"><a href="../appendices/a04-tesla-rivian.html"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Tesla and Rivian: Company Connections</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">ACCTG 211H Companion</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/sbb151/acctg211h-companion" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface: Reading, Practice, and Evidence</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Arc I — Information, Value, and Reporting</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc1-information/01-information.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Why Accounting? Information and Cooperation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc1-information/02-certainty.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Value and Income Under Certainty</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc1-information/03-uncertainty.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Value and Income Under Uncertainty</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc1-information/04-information-incentives.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Information, Credibility, and Incentives</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc1-information/05-framework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">From Economic Questions to Accounting Reports</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Arc II — Markets and Measurement</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc2-markets/06-efficient-markets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Efficient Markets and the Information Content of Earnings</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc2-markets/07-accruals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Cash Flows, Accruals, and Earnings Quality</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc2-markets/08-long-term-assets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Long-Term Assets and Measurement Choice</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc2-markets/09-liabilities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Liabilities, Debt Covenants, and Conservatism</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc2-markets/10-equity-compensation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Equity, Compensation, and Reporting Incentives</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Arc III — Contracting and Internal Information</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc3-internal/11-decentralization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Decentralization and Cost Behavior</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc3-internal/12-performance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Performance Measurement as Agency</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc3-internal/13-capital-budgeting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Capital Budgeting Under Asymmetric Information</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Arc IV — Synthesis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../arc4-synthesis/14-debates.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Synthesis: The Capstone Debates</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/a01-fset.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">A1. The Financial Statement Effects Template</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/a02-python-wrds-colab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">A2. Python + WRDS in Google Colab Quickstart</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/a03-debits-credits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">A3. Debits and Credits</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/a04-tesla-rivian.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Tesla and Rivian: Company Connections</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#company-source-card" id="toc-company-source-card" class="nav-link active" data-scroll-target="#company-source-card"><span class="header-section-number">D.1</span> Source card: a fixed annual-report snapshot</a></li>
  <li><a href="#company-c01" id="toc-company-c01" class="nav-link" data-scroll-target="#company-c01"><span class="header-section-number">D.2</span> Chapter 1: Who needs information?</a></li>
  <li><a href="#company-c02" id="toc-company-c02" class="nav-link" data-scroll-target="#company-c02"><span class="header-section-number">D.3</span> Chapter 2: Model value and reported assets</a></li>
  <li><a href="#company-c03" id="toc-company-c03" class="nav-link" data-scroll-target="#company-c03"><span class="header-section-number">D.4</span> Chapter 3: News and uncertainty</a></li>
  <li><a href="#company-c04" id="toc-company-c04" class="nav-link" data-scroll-target="#company-c04"><span class="header-section-number">D.5</span> Chapter 4: Reports and incentives</a></li>
  <li><a href="#company-c05" id="toc-company-c05" class="nav-link" data-scroll-target="#company-c05"><span class="header-section-number">D.6</span> Chapter 5: What does a statement measure?</a></li>
  <li><a href="#company-c06" id="toc-company-c06" class="nav-link" data-scroll-target="#company-c06"><span class="header-section-number">D.7</span> Chapter 6: News requires expectations</a></li>
  <li><a href="#company-c07" id="toc-company-c07" class="nav-link" data-scroll-target="#company-c07"><span class="header-section-number">D.8</span> Chapter 7: Earnings and operating cash</a></li>
  <li><a href="#company-c08" id="toc-company-c08" class="nav-link" data-scroll-target="#company-c08"><span class="header-section-number">D.9</span> Chapter 8: Resources, estimates, and expenditure</a></li>
  <li><a href="#company-c09" id="toc-company-c09" class="nav-link" data-scroll-target="#company-c09"><span class="header-section-number">D.10</span> Chapter 9: Financing and contract definitions</a></li>
  <li><a href="#company-c10" id="toc-company-c10" class="nav-link" data-scroll-target="#company-c10"><span class="header-section-number">D.11</span> Chapter 10: Whose earnings per share?</a></li>
  <li><a href="#company-c11" id="toc-company-c11" class="nav-link" data-scroll-target="#company-c11"><span class="header-section-number">D.12</span> Chapter 11: Gross profit is not contribution margin</a></li>
  <li><a href="#company-c12" id="toc-company-c12" class="nav-link" data-scroll-target="#company-c12"><span class="header-section-number">D.13</span> Chapter 12: Evaluate a manager’s choices</a></li>
  <li><a href="#company-c13" id="toc-company-c13" class="nav-link" data-scroll-target="#company-c13"><span class="header-section-number">D.14</span> Chapter 13: Investment requires incremental cash flows</a></li>
  <li><a href="#company-c14" id="toc-company-c14" class="nav-link" data-scroll-target="#company-c14"><span class="header-section-number">D.15</span> Chapter 14: Familiar firms, precise policy claims</a></li>
  <li><a href="#the-empirical-project-remains-a-separate-comparison" id="toc-the-empirical-project-remains-a-separate-comparison" class="nav-link" data-scroll-target="#the-empirical-project-remains-a-separate-comparison"><span class="header-section-number">D.16</span> The empirical project remains a separate comparison</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/sbb151/acctg211h-companion/edit/main/appendices/a04-tesla-rivian.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/sbb151/acctg211h-companion/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../appendices/a01-fset.html">Appendices</a></li><li class="breadcrumb-item"><a href="../appendices/a04-tesla-rivian.html"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Tesla and Rivian: Company Connections</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-company-connections" class="quarto-section-identifier">Appendix D — Tesla and Rivian: Company Connections</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Tesla is our recurring company example; Rivian provides a useful comparison. These short connections transfer each chapter’s ideas to familiar companies. The instructor selects prompts within existing class time. They do not add a full annual-report reading, a new submission, or facts to memorize for an exam.</p>
<p><strong>Evidence rule:</strong> the source card below contains reported observations. Prompts labeled <strong>constructed</strong> supply teaching assumptions, not either company’s actual forecasts, contracts, unit costs, or employee behavior. Campus Curb remains the small linked model used to learn statement mechanics. Keep its balances separate from company observations.</p>
<section id="company-source-card" class="level2" data-number="D.1">
<h2 data-number="D.1" class="anchored" data-anchor-id="company-source-card"><span class="header-section-number">D.1</span> Source card: a fixed annual-report snapshot</h2>
<p>Fiscal years end December 31. All amounts below are <strong>USD millions</strong>; parentheses indicate negative amounts. The figures come from the fiscal 2025 Forms 10-K, checked September 23, 2026. This fixed teaching snapshot is not a current stock recommendation or a point-in-time trading dataset.</p>
<div class="a11y-table-region" role="region" tabindex="0" aria-label="Scrollable data table">
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Reported measure</th>
<th style="text-align: right;">Tesla 2024</th>
<th style="text-align: right;">Tesla 2025</th>
<th style="text-align: right;">Rivian 2024</th>
<th style="text-align: right;">Rivian 2025</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Revenue</td>
<td style="text-align: right;">97,690</td>
<td style="text-align: right;">94,827</td>
<td style="text-align: right;">4,970</td>
<td style="text-align: right;">5,387</td>
</tr>
<tr class="even">
<td>Gross profit (loss)</td>
<td style="text-align: right;">17,450</td>
<td style="text-align: right;">17,094</td>
<td style="text-align: right;">(1,200)</td>
<td style="text-align: right;">144</td>
</tr>
<tr class="odd">
<td>Operating income (loss)</td>
<td style="text-align: right;">7,076</td>
<td style="text-align: right;">4,355</td>
<td style="text-align: right;">(4,689)</td>
<td style="text-align: right;">(3,585)</td>
</tr>
<tr class="even">
<td>Consolidated net income (loss)</td>
<td style="text-align: right;">7,153</td>
<td style="text-align: right;">3,855</td>
<td style="text-align: right;">(4,746)</td>
<td style="text-align: right;">(3,626)</td>
</tr>
<tr class="odd">
<td>Cash flow from operations (CFO)</td>
<td style="text-align: right;">14,923</td>
<td style="text-align: right;">14,747</td>
<td style="text-align: right;">(1,716)</td>
<td style="text-align: right;">(779)</td>
</tr>
<tr class="even">
<td>Total assets at year-end</td>
<td style="text-align: right;">122,070</td>
<td style="text-align: right;">137,806</td>
<td style="text-align: right;">15,410</td>
<td style="text-align: right;">14,864</td>
</tr>
</tbody>
</table>
</div>
<p>Sources: <a href="https://www.sec.gov/Archives/edgar/data/1318605/000162828026003952/tsla-20251231.htm">Tesla 2025 Form 10-K</a>, printed pp.&nbsp;49, 50, 53; <a href="https://www.sec.gov/Archives/edgar/data/1874178/000187417826000008/rivn-20251231.htm">Rivian 2025 Form 10-K</a>, printed pp.&nbsp;74, 75, 77. These SEC links are public; no library subscription or WRDS account is needed. Read only the indicated statement/table when directed.</p>
<p>Use consolidated net income when comparing with consolidated CFO. Common-stockholder income has a different scope and is the relevant numerator for basic EPS. Revenue, gross profit, operating income, net income, and CFO answer different questions. CFO excludes investing cash flows; it is not cash remaining after all investment needs.</p>
</section>
<section id="company-c01" class="level2" data-number="D.2">
<h2 data-number="D.2" class="anchored" data-anchor-id="company-c01"><span class="header-section-number">D.2</span> Chapter 1: Who needs information?</h2>
<p>Imagine applying to work for Tesla or supplying parts to Rivian. What report would change your decision? Identify one question about resources, one about obligations, and one about how management uses entrusted resources.</p>
<p><strong>Constructed used-EV transfer:</strong> a seller knows a used Tesla’s battery condition and the buyer does not. Explain hidden information and selection. A future maintenance choice that a customer cannot observe instead involves hidden action. These hypothetical roles make no allegation about Tesla, Rivian, or a particular seller.</p>
</section>
<section id="company-c02" class="level2" data-number="D.3">
<h2 data-number="D.3" class="anchored" data-anchor-id="company-c02"><span class="header-section-number">D.3</span> Chapter 2: Model value and reported assets</h2>
<p><strong>Constructed:</strong> a charging installation costs its model present value and pays 60 at each of two year-ends, then expires. Cash flows are certain, the rate is 10%, and every receipt is distributed. Compute opening value, value immediately after the first distribution, and first-year economic income. Explain why this does not prescribe either company’s GAAP balance-sheet value.</p>
<p>Self-check: opening value 104.13; remaining value 54.55; income 10.41. The first receipt includes both return of capital and income.</p>
</section>
<section id="company-c03" class="level2" data-number="D.4">
<h2 data-number="D.4" class="anchored" data-anchor-id="company-c03"><span class="header-section-number">D.4</span> Chapter 3: News and uncertainty</h2>
<p><strong>Constructed continuation:</strong> the installation still pays 60 in year 1. Year-2 cash is now 80 or 40 with equal probabilities; everyone initially knows these probabilities. The state is learned just before the first distribution. Compare the two end-year-1 values and economic incomes. Does uncertainty by itself establish that someone has private information?</p>
<p>Self-check: values 72.73/36.36; incomes 28.60/(7.77); expected income 10.41. These are teaching cash flows, not Tesla or Rivian guidance.</p>
</section>
<section id="company-c04" class="level2" data-number="D.5">
<h2 data-number="D.5" class="anchored" data-anchor-id="company-c04"><span class="header-section-number">D.5</span> Chapter 4: Reports and incentives</h2>
<p><strong>Constructed:</strong> an EV service manager receives a bonus for completed jobs. Identify a potentially hidden action, a noisy outcome, and a verification method. Compare completed jobs with a measure that also considers verified repair quality. What behavior could the added measure distort? The exercise does not describe an actual company’s compensation plan.</p>
</section>
<section id="company-c05" class="level2" data-number="D.6">
<h2 data-number="D.6" class="anchored" data-anchor-id="company-c05"><span class="header-section-number">D.6</span> Chapter 5: What does a statement measure?</h2>
<p>Use the source card to locate a stock measured at a date and a flow measured over a year. A prospective employee asks whether a large asset balance guarantees payroll can be met: what additional evidence would help? Keep conceptual definitions, recognition rules, measurement, and disclosure distinct. Continue using the small Campus Curb case for complete transaction-to-statement practice.</p>
</section>
<section id="company-c06" class="level2" data-number="D.7">
<h2 data-number="D.7" class="anchored" data-anchor-id="company-c06"><span class="header-section-number">D.7</span> Chapter 6: News requires expectations</h2>
<p>Tesla’s annual revenue changes in the source card do not by themselves identify an earnings surprise or an abnormal stock return. What expectation, release timestamp, market comparison, and competing news would an announcement analysis need? Use the supplied Lab 1 returns to learn the calculation; do not describe those constructed returns as Tesla observations.</p>
</section>
<section id="company-c07" class="level2" data-number="D.8">
<h2 data-number="D.8" class="anchored" data-anchor-id="company-c07"><span class="header-section-number">D.8</span> Chapter 7: Earnings and operating cash</h2>
<p>For 2025, compute <strong>CFO minus consolidated net income</strong> for each company. Find at least one reconciliation category in the indicated cash-flow statement. Explain why the gap alone is not a measure of fraud or discretionary accruals. Explain why negative net income and less-negative CFO can coexist.</p>
<p>Self-check: Tesla 10,892; Rivian 2,847. The full reconciliations include noncash adjustments and operating-asset/liability changes. No single adjustment should be assumed to explain the entire gap. These two-company observations do not reproduce Sloan’s sample, earnings measure, or return test.</p>
</section>
<section id="company-c08" class="level2" data-number="D.9">
<h2 data-number="D.9" class="anchored" data-anchor-id="company-c08"><span class="header-section-number">D.9</span> Chapter 8: Resources, estimates, and expenditure</h2>
<p>Use either company’s balance sheet to distinguish inventory from property, plant, and equipment. <strong>Constructed transfer:</strong> apply the chapter’s machine example to equipment in a hypothetical EV workshop. Which costs prepare it for use? What evidence supports its life and impairment inputs? A company’s expenditure does not by itself establish fair value or the present value of benefits. Do not apply one impairment rule to every asset.</p>
</section>
<section id="company-c09" class="level2" data-number="D.10">
<h2 data-number="D.10" class="anchored" data-anchor-id="company-c09"><span class="header-section-number">D.10</span> Chapter 9: Financing and contract definitions</h2>
<p>Imagine evaluating financing for a Rivian supplier. What contractual information would you request before calculating covenant slack? Keep the chapter’s supplied definitions and numerical loan separate from any actual company’s borrowing. A balance-sheet amount does not reveal every covenant, testing date, permitted adjustment, or remedy; a negative income figure is not itself a covenant violation.</p>
</section>
<section id="company-c10" class="level2" data-number="D.11">
<h2 data-number="D.11" class="anchored" data-anchor-id="company-c10"><span class="header-section-number">D.11</span> Chapter 10: Whose earnings per share?</h2>
<p>Tesla’s 2025 statement reports net income attributable to common stockholders of <strong>3,794 million</strong> and weighted-average basic shares of <strong>3,225 million</strong>. Divide the matching amounts to reproduce basic EPS rounded to cents: <strong>1.18</strong>. The consolidated income figure in the source card is <strong>3,855 million</strong> and is not this EPS numerator. Source: Tesla Form 10-K, printed p.&nbsp;50.</p>
<p>For employee awards, use the chapter’s simple equity-classified service-award assumptions. Do not treat that example as a reconstruction of an actual Tesla executive award. Explain why paying in equity can impose an economic cost even without a current cash payment.</p>
</section>
<section id="company-c11" class="level2" data-number="D.12">
<h2 data-number="D.12" class="anchored" data-anchor-id="company-c11"><span class="header-section-number">D.12</span> Chapter 11: Gross profit is not contribution margin</h2>
<p>Rivian moves from a gross loss of 1,200 in 2024 to gross profit of 144 in 2025 while reporting operating losses in both years. Compute the gross-profit change and reconcile 2025 gross profit to operating loss using operating expenses of 3,729. Source: Rivian Form 10-K, printed p.&nbsp;75.</p>
<p>Self-check: gross profit improves by 1,344; 144 minus 3,729 equals (3,585). Neither gross profit nor two years of revenue and operating income supplies the fixed/variable cost split needed for contribution-margin analysis. Use the constructed festival case for the mechanics, then identify the missing company information.</p>
</section>
<section id="company-c12" class="level2" data-number="D.13">
<h2 data-number="D.13" class="anchored" data-anchor-id="company-c12"><span class="header-section-number">D.13</span> Chapter 12: Evaluate a manager’s choices</h2>
<p><strong>Constructed:</strong> an EV service center is judged on jobs completed, cost, repair quality, and operating capital. Use the chapter’s matched ROI/RI and variance examples to ask what the manager controls and what demand, parts quality, or equipment condition also affects. Name an independent check and a potential unintended response. A variance is a reason to investigate, not proof of low effort.</p>
</section>
<section id="company-c13" class="level2" data-number="D.14">
<h2 data-number="D.14" class="anchored" data-anchor-id="company-c13"><span class="header-section-number">D.14</span> Chapter 13: Investment requires incremental cash flows</h2>
<p><strong>Constructed:</strong> Tesla or Rivian is considering a charging, service, or manufacturing project. Use the chapter’s supplied cash flows and discount rate, not invented company forecasts. State the alternative, timing, opportunity costs, and information that a project sponsor might privately hold. Keep the same underlying states and costs when valuing flexibility. Growth, expenditure, or a prominent product announcement alone does not establish positive NPV.</p>
</section>
<section id="company-c14" class="level2" data-number="D.15">
<h2 data-number="D.15" class="anchored" data-anchor-id="company-c14"><span class="header-section-number">D.15</span> Chapter 14: Familiar firms, precise policy claims</h2>
<p>Use Tesla or Rivian to name a user and decision in the climate, equity-compensation, and sustainability debates. For a goodwill question, explicitly posit a hypothetical acquisition; do not invent an acquisition or goodwill balance. The common debate resolutions and rubrics remain authoritative. Separate a policy proposal, a reported fact, and a causal claim. A company’s familiarity is not evidence that one side’s argument is correct.</p>
</section>
<section id="the-empirical-project-remains-a-separate-comparison" class="level2" data-number="D.16">
<h2 data-number="D.16" class="anchored" data-anchor-id="the-empirical-project-remains-a-separate-comparison"><span class="header-section-number">D.16</span> The empirical project remains a separate comparison</h2>
<p>The supplied project keeps its 12-retailer panel, common measurement rules, and 24 prediction pairs. Tesla and Rivian are classroom connections, not silently added observations or substitutes for the pre-specified sample. Explain what would need to change before transferring a retailer result to EV firms. No new data collection, programming, or student WRDS login is assigned.</p>


<!-- -->

</section>

</main> <!-- /main -->
<footer class="course-accessibility"><p><a href="https://www.psu.edu/accessibilitystatement">Penn State accessibility statement</a> · <a href="mailto:accessibility@psu.edu">Report an accessibility barrier to the Penn State IT Accessibility Team</a>. Include the page address and a description of the issue.</p></footer>
<script>
document.addEventListener('DOMContentLoaded', function () {
  document.querySelectorAll('main table').forEach(function (table) {
    table.querySelectorAll('thead th').forEach(function (th) { th.scope = 'col'; });
    table.querySelectorAll('tbody tr').forEach(function (row) {
      var first = row.firstElementChild;
      if (first && first.tagName === 'TD' && first.textContent.trim()) {
        var th = document.createElement('th');
        th.scope = 'row'; th.innerHTML = first.innerHTML;
        th.style.cssText = first.style.cssText; th.style.fontWeight = 'normal';
        first.replaceWith(th);
      }
    });
    var region = table.closest('.a11y-table-region');
    if (region && region.getAttribute('aria-label') === 'Scrollable data table') {
      var section = table.closest('section');
      var heading = section && section.querySelector('h1,h2,h3,h4,h5,h6');
      if (heading) region.setAttribute('aria-label', heading.textContent.trim() + ' — data table');
    }
  });
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/sbb151\.github\.io\/acctg211h-companion\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../appendices/a03-debits-credits.html" class="pagination-link" aria-label="A3. Debits and Credits">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">A3. Debits and Credits</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Tesla and Rivian examples connecting information, statements, incentives, and investment decisions."</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu"># Tesla and Rivian: Company Connections {#sec-company-connections}</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>Tesla is our recurring company example; Rivian provides a useful comparison. These short connections transfer each chapter's ideas to familiar companies. The instructor selects prompts within existing class time. They do not add a full annual-report reading, a new submission, or facts to memorize for an exam.</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>**Evidence rule:** the source card below contains reported observations. Prompts labeled **constructed** supply teaching assumptions, not either company's actual forecasts, contracts, unit costs, or employee behavior. Campus Curb remains the small linked model used to learn statement mechanics. Keep its balances separate from company observations.</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">## Source card: a fixed annual-report snapshot {#company-source-card}</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>Fiscal years end December 31. All amounts below are **USD millions**; parentheses indicate negative amounts. The figures come from the fiscal 2025 Forms 10-K, checked September 23, 2026. This fixed teaching snapshot is not a current stock recommendation or a point-in-time trading dataset.</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>| Reported measure | Tesla 2024 | Tesla 2025 | Rivian 2024 | Rivian 2025 |</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>|---|---:|---:|---:|---:|</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>| Revenue | 97,690 | 94,827 | 4,970 | 5,387 |</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>| Gross profit (loss) | 17,450 | 17,094 | (1,200) | 144 |</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>| Operating income (loss) | 7,076 | 4,355 | (4,689) | (3,585) |</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>| Consolidated net income (loss) | 7,153 | 3,855 | (4,746) | (3,626) |</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>| Cash flow from operations (CFO) | 14,923 | 14,747 | (1,716) | (779) |</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>| Total assets at year-end | 122,070 | 137,806 | 15,410 | 14,864 |</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>Sources: <span class="co">[</span><span class="ot">Tesla 2025 Form 10-K</span><span class="co">](https://www.sec.gov/Archives/edgar/data/1318605/000162828026003952/tsla-20251231.htm)</span>, printed pp. 49, 50, 53; <span class="co">[</span><span class="ot">Rivian 2025 Form 10-K</span><span class="co">](https://www.sec.gov/Archives/edgar/data/1874178/000187417826000008/rivn-20251231.htm)</span>, printed pp. 74, 75, 77. These SEC links are public; no library subscription or WRDS account is needed. Read only the indicated statement/table when directed.</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>Use consolidated net income when comparing with consolidated CFO. Common-stockholder income has a different scope and is the relevant numerator for basic EPS. Revenue, gross profit, operating income, net income, and CFO answer different questions. CFO excludes investing cash flows; it is not cash remaining after all investment needs.</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="fu">## Chapter 1: Who needs information? {#company-c01}</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>Imagine applying to work for Tesla or supplying parts to Rivian. What report would change your decision? Identify one question about resources, one about obligations, and one about how management uses entrusted resources.</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>**Constructed used-EV transfer:** a seller knows a used Tesla's battery condition and the buyer does not. Explain hidden information and selection. A future maintenance choice that a customer cannot observe instead involves hidden action. These hypothetical roles make no allegation about Tesla, Rivian, or a particular seller.</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="fu">## Chapter 2: Model value and reported assets {#company-c02}</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>**Constructed:** a charging installation costs its model present value and pays 60 at each of two year-ends, then expires. Cash flows are certain, the rate is 10%, and every receipt is distributed. Compute opening value, value immediately after the first distribution, and first-year economic income. Explain why this does not prescribe either company's GAAP balance-sheet value.</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>Self-check: opening value 104.13; remaining value 54.55; income 10.41. The first receipt includes both return of capital and income.</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a><span class="fu">## Chapter 3: News and uncertainty {#company-c03}</span></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>**Constructed continuation:** the installation still pays 60 in year 1. Year-2 cash is now 80 or 40 with equal probabilities; everyone initially knows these probabilities. The state is learned just before the first distribution. Compare the two end-year-1 values and economic incomes. Does uncertainty by itself establish that someone has private information?</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>Self-check: values 72.73/36.36; incomes 28.60/(7.77); expected income 10.41. These are teaching cash flows, not Tesla or Rivian guidance.</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a><span class="fu">## Chapter 4: Reports and incentives {#company-c04}</span></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>**Constructed:** an EV service manager receives a bonus for completed jobs. Identify a potentially hidden action, a noisy outcome, and a verification method. Compare completed jobs with a measure that also considers verified repair quality. What behavior could the added measure distort? The exercise does not describe an actual company's compensation plan.</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a><span class="fu">## Chapter 5: What does a statement measure? {#company-c05}</span></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>Use the source card to locate a stock measured at a date and a flow measured over a year. A prospective employee asks whether a large asset balance guarantees payroll can be met: what additional evidence would help? Keep conceptual definitions, recognition rules, measurement, and disclosure distinct. Continue using the small Campus Curb case for complete transaction-to-statement practice.</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a><span class="fu">## Chapter 6: News requires expectations {#company-c06}</span></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>Tesla's annual revenue changes in the source card do not by themselves identify an earnings surprise or an abnormal stock return. What expectation, release timestamp, market comparison, and competing news would an announcement analysis need? Use the supplied Lab 1 returns to learn the calculation; do not describe those constructed returns as Tesla observations.</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a><span class="fu">## Chapter 7: Earnings and operating cash {#company-c07}</span></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>For 2025, compute **CFO minus consolidated net income** for each company. Find at least one reconciliation category in the indicated cash-flow statement. Explain why the gap alone is not a measure of fraud or discretionary accruals. Explain why negative net income and less-negative CFO can coexist.</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>Self-check: Tesla 10,892; Rivian 2,847. The full reconciliations include noncash adjustments and operating-asset/liability changes. No single adjustment should be assumed to explain the entire gap. These two-company observations do not reproduce Sloan's sample, earnings measure, or return test.</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a><span class="fu">## Chapter 8: Resources, estimates, and expenditure {#company-c08}</span></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>Use either company's balance sheet to distinguish inventory from property, plant, and equipment. **Constructed transfer:** apply the chapter's machine example to equipment in a hypothetical EV workshop. Which costs prepare it for use? What evidence supports its life and impairment inputs? A company's expenditure does not by itself establish fair value or the present value of benefits. Do not apply one impairment rule to every asset.</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a><span class="fu">## Chapter 9: Financing and contract definitions {#company-c09}</span></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>Imagine evaluating financing for a Rivian supplier. What contractual information would you request before calculating covenant slack? Keep the chapter's supplied definitions and numerical loan separate from any actual company's borrowing. A balance-sheet amount does not reveal every covenant, testing date, permitted adjustment, or remedy; a negative income figure is not itself a covenant violation.</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a><span class="fu">## Chapter 10: Whose earnings per share? {#company-c10}</span></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>Tesla's 2025 statement reports net income attributable to common stockholders of **3,794 million** and weighted-average basic shares of **3,225 million**. Divide the matching amounts to reproduce basic EPS rounded to cents: **1.18**. The consolidated income figure in the source card is **3,855 million** and is not this EPS numerator. Source: Tesla Form 10-K, printed p. 50.</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>For employee awards, use the chapter's simple equity-classified service-award assumptions. Do not treat that example as a reconstruction of an actual Tesla executive award. Explain why paying in equity can impose an economic cost even without a current cash payment.</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a><span class="fu">## Chapter 11: Gross profit is not contribution margin {#company-c11}</span></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>Rivian moves from a gross loss of 1,200 in 2024 to gross profit of 144 in 2025 while reporting operating losses in both years. Compute the gross-profit change and reconcile 2025 gross profit to operating loss using operating expenses of 3,729. Source: Rivian Form 10-K, printed p. 75.</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>Self-check: gross profit improves by 1,344; 144 minus 3,729 equals (3,585). Neither gross profit nor two years of revenue and operating income supplies the fixed/variable cost split needed for contribution-margin analysis. Use the constructed festival case for the mechanics, then identify the missing company information.</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a><span class="fu">## Chapter 12: Evaluate a manager's choices {#company-c12}</span></span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a>**Constructed:** an EV service center is judged on jobs completed, cost, repair quality, and operating capital. Use the chapter's matched ROI/RI and variance examples to ask what the manager controls and what demand, parts quality, or equipment condition also affects. Name an independent check and a potential unintended response. A variance is a reason to investigate, not proof of low effort.</span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a><span class="fu">## Chapter 13: Investment requires incremental cash flows {#company-c13}</span></span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a>**Constructed:** Tesla or Rivian is considering a charging, service, or manufacturing project. Use the chapter's supplied cash flows and discount rate, not invented company forecasts. State the alternative, timing, opportunity costs, and information that a project sponsor might privately hold. Keep the same underlying states and costs when valuing flexibility. Growth, expenditure, or a prominent product announcement alone does not establish positive NPV.</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a><span class="fu">## Chapter 14: Familiar firms, precise policy claims {#company-c14}</span></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a>Use Tesla or Rivian to name a user and decision in the climate, equity-compensation, and sustainability debates. For a goodwill question, explicitly posit a hypothetical acquisition; do not invent an acquisition or goodwill balance. The common debate resolutions and rubrics remain authoritative. Separate a policy proposal, a reported fact, and a causal claim. A company's familiarity is not evidence that one side's argument is correct.</span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a><span class="fu">## The empirical project remains a separate comparison</span></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a>The supplied project keeps its 12-retailer panel, common measurement rules, and 24 prediction pairs. Tesla and Rivian are classroom connections, not silently added observations or substitutes for the pre-specified sample. Explain what would need to change before transferring a retailer result to EV firms. No new data collection, programming, or student WRDS login is assigned.</span></code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/sbb151/acctg211h-companion/edit/main/appendices/a04-tesla-rivian.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/sbb151/acctg211h-companion/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>